### ISSUE TITLE
Carthage failed with exit code 65

### ISSUE THREAD

**Issue by abhinavnair** [ninjaprox/NVActivityIndicatorView#101]
I am having trouble installing with Carthage. 
I ran - `carthage update --platform iOS --no-use-binaries`
I am using this on macOS Sierra with Xcode 8.2 and targetting Swift 3.0.1. I have successfully installed it on another system with the exact same configuration yesterday but not able to do so on this one.

My cartfile has this line - `github "ninjaprox/NVActivityIndicatorView" "v3.1"`

The error is :-

```
*** Building scheme "NVActivityIndicatorView" in NVActivityIndicatorView.xcodeproj
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/abhinavnair/pem-ios/PEM/Carthage/Checkouts/NVActivityIndicatorView/NVActivityIndicatorView.xcodeproj -scheme NVActivityIndicatorView -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

**Comment by vincentsaluzzo** [comment]
Resolved in #102

**Comment by vincentsaluzzo** [comment]
waiting for PR approval by @ninjaprox

**Comment by ninjaprox** [comment]
@abhinavnair, @vincentsaluzzo: Merged to `carthage` branch, please use it instead of `master` for the moment.

**Comment by lzhlewis2015** [comment]
@ninjaprox thank you for answer my question , but I just dont't know how to user Carthage to merged to the carthage branch . I just add     "github ninjaprox/NVActivityIndicatorView" to the cartfile and run "carthage update "  ,can you tell the detail method that I can use the "carthage" branch  .

**Comment by ninjaprox** [comment]
@lzhlewis2015: It should be `github ninjaprox/NVActivityIndicatorView "carthage"`. You can also check [this reference](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#version-requirement).
