### ISSUE TITLE
Carthage install fails

### ISSUE THREAD

**Issue by theceremony** [ninjaprox/NVActivityIndicatorView#105]
The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project "/Users/jeramymorrill/Work Bench/blueberry/Blueberry-Voice-Recorder/Carthage/Checkouts/NVActivityIndicatorView/NVActivityIndicatorView.xcodeproj" -scheme NVActivityIndicatorView -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **

**Comment by walsht** [comment]
+1

**Comment by lzhlewis2015** [comment]
I face the same problem just now

**Comment by walsht** [comment]
I found this... https://github.com/ninjaprox/NVActivityIndicatorView/issues/101

**Comment by lzhlewis2015** [comment]
@walsht I change the SWIFT_VERSION to 3.0 ,but when I run carthage udpate ,the file run back to the origin one (SWIFT_VERSION) ,how do you solve this problem?

**Comment by ninjaprox** [comment]
@theceremony, @lzhlewis2015:  How about using `carthage` branch? I hope it would help.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
