### ISSUE TITLE
pod install just got 2.9 not 3.0

### ISSUE THREAD

**Issue by lucasjinreal** [ninjaprox/NVActivityIndicatorView#106]
simply pod 'NVActivityIndicatorView', but when I pod install, it only got 2.9 version, I am using Swift3, how can I got the 3.0 version?

**Comment by ninjaprox** [comment]
@jinfagang: Hmm... it's weird. I've just tried myself and got 3.1 (the latest one). How about `pod 'NVActivityIndicatorView', '3.0'`?

**Comment by Laptopmini** [comment]
Update your specs-repos
```
pod repo update
```

**Comment by lucasjinreal** [comment]
ok, thank you very much, I will try it.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
