### ISSUE TITLE
Type 'NVActivityIndicatorPresenter' has no member 'sharedInstance'

### ISSUE THREAD

**Issue by ghost** [ninjaprox/NVActivityIndicatorView#107]
# Context
Swift 2.3

# Installation
Using Carthage:
`github "ninjaprox/NVActivityIndicatorView" "swift2.3" `

# Code
```
    let activityData = ActivityData()
    NVActivityIndicatorPresenter.sharedInstance.startAnimating(activityData)
```

# Error
<img width="681" alt="capture d ecran 2017-01-10 a 05 26 43" src="https://cloud.githubusercontent.com/assets/385357/21793859/6c6d20d8-d6f5-11e6-907d-1e9a5bc9295a.png">

**Comment by ninjaprox** [comment]
@Domsware: Oh the `sharedInstance` was internal. Updated, should work now.

**Comment by ghost** [comment]
Great! It works!
