### ISSUE TITLE
An message

### ISSUE THREAD

**Issue by midgard** [ninjaprox/NVActivityIndicatorView#111]
I'm using facebook login.

My app going to facebook (app) and come back, and i'm starting animation.

And i'm getting this:

Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.

**Comment by Laptopmini** [comment]
Please provide at least some lines of your code; where the error was thrown for example.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
