### ISSUE TITLE
If the DGActivityIndicatorView.m document rewrite - (instancetype) init method, which is more perfect!

### ISSUE THREAD

**Issue by kb100824** [ninjaprox/NVActivityIndicatorView#112]
I add the rewrite - (instancetype) init method to the DGActivityIndicatorView.m file to easily support NSLayoutConstraint to set its location:

- (instancetype)init{

    if (self = [super init]) {
        _tintColor = [UIColor whiteColor];
        _size = kDGActivityIndicatorDefaultSize;
        [self commonInit];
    }
    return self;
    
}

**Comment by ninjaprox** [comment]
@KBvsMJ: Sorry, I didn't get you. Could you elaborate more?

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
