### ISSUE TITLE
Layout issue - shadow view not cover all screen.

### ISSUE THREAD

**Issue by vkornieiev** [ninjaprox/NVActivityIndicatorView#115]
Layout issue - shadow view not cover all screen if device changing orientation during indicator show.
Please add layout constraints to shadow view if it possible. Thank you!

**Comment by ninjaprox** [comment]
@fasteroko: Thanks for reporting, I'll take a look at this. As usual, PR is welcome.

**Comment by vkornieiev** [comment]
PR is available now. Hope it will be useful for you 👍 
Vladyslav (fasteroko).

**Comment by ninjaprox** [comment]
Merged. Thanks for your PR 👍.

**Comment by vkornieiev** [comment]
You are welcome
​ :)


2017-01-31 14:54 GMT+02:00 Vinh Nguyen <notifications@github.com>:

**Comment by vkornieiev** [comment]
Do you know when this
​ ​
update will be available via cocoapods?
​​

2017-01-31 14:54 GMT+02:00 Vinh Nguyen <notifications@github.com>:

**Comment by ninjaprox** [comment]
@fasteroko: It's on the way 🚀. Let's check out in 15 mins.

**Comment by vkornieiev** [comment]
Awesome! Thank you! :)

2017-01-31 16:06 GMT+02:00 Vinh Nguyen <notifications@github.com>:
