### ISSUE TITLE
Initialization Problem

### ISSUE THREAD

**Issue by kuraydev** [ninjaprox/NVActivityIndicatorView#122]
Hello, 
First of all thank you for this amazing lib :) 
I'm kinda new at iOS and i have a little trouble about initialization. 

Here is my code : 

 let width = Int(self.view.frame.width / 2)
        let height = Int(self.view.frame.height / 2)
        let x = 0
        let y = 0
        let frame = CGRect(x: x, y: y, width: width, height: height)
        let activityIndicatorView = NVActivityIndicatorView(frame: frame, type: .audioEqualizer, color: .black)
         activityIndicatorView.startAnimating()

I tried to show an indicator appear on the center but nothing appears. I tried yours Default setting. It is working but i want to customise it. 

Can you teach me how to use it? 
Thank you :)

**Comment by ninjaprox** [comment]
@WrathChaos: Have you added the `activityIndicatorView` to the `view`? I hope it's the missing part. Let me know if it doesn't help.

**Comment by kuraydev** [comment]
@ninjaprox Yay! Thank you, i forgot to add to the view. One more question, when i make the width, height as self.view.frame.width and height, Main indicator looks too big how can i make it smaller but background should be fullscreen?

Thank you again :)

**Comment by ninjaprox** [comment]
@WrathChaos: You can set `padding` so that the size of indicator view is as same as `view.frame.size`, but the size of the animation is calculated based on that.

**Comment by kuraydev** [comment]
@ninjaprox  Thank you so much for helping :) That is a great library!
