### ISSUE TITLE
UI blocker: conflict of states (dead end if tries to stop animation in hidden state)

### ISSUE THREAD

**Issue by Vinzius** [ninjaprox/NVActivityIndicatorView#123]
Hi !

First, thank you for your library.

I may have found a problem when calling the methods in a weird way.

Problem: when calling `startAnimating()`, if state is not `.hidden`, then blocker won't display. But sometimes state isn't hidden while blocker isn't going to hide !

How:
- Step 0: `state = .hidden`
- Step 1: Calling `NVActivityIndicatorPresenter.sharedInstance.stopAnimating()` So `state = .waitingToHide`
- Step 2: Calling `NVActivityIndicatorPresenter.sharedInstance.startAnimating(activityData)`. But `state == .waitingToHide`, so `guard state == .hidden else { return }` will avoid the display.

Idea to solve: in `_hide`, do: `else if self.state != .hidden { }` instead of the `else`. Not 100% sure it'll handle all cases, but I think it would do.

Why calling stopAnimation() first ?
I would need a way to check if the UI blocker is being displayed or not. So in some cases I could hide it (like during log-out).
Yes I could wrap the calls and create my own tag, but I think it should be handled by the library and this kind of conflict could be avoided.

I can do a PR if you want. Just le me know.

Thanks :-)

**Comment by ninjaprox** [comment]
@Vinzius: Thanks for reporting! I'm surprised that how I could miss that obvious use case. Your proposition seems good and I think it suffices to handle all cases. However, if finding any case might break the behavior, please create an issue. PR is always welcome.

**Comment by Vinzius** [comment]
Sure, you're welcome.
So do you want a PR for this one too? (I don't mind, it's just only a few chars :p)

**Comment by ninjaprox** [comment]
Yes sure 👍

**Comment by Vinzius** [comment]
Ok! Will do today :-)
