### ISSUE TITLE
error due to animation.setUpAnimation()

### ISSUE THREAD

**Issue by pbeneteau** [ninjaprox/NVActivityIndicatorView#125]
My app crash because of that function(EXC_BAD_ACCESS): 

 animation.setUpAnimation(in: layer, size: animationRect.size, color: color);

 in NVActivityIndicatorView.swift line 456.

No logs.

**Comment by pbeneteau** [comment]
Found solution: REPLACE first uppercase of type names by a lowercase.

**Comment by pbeneteau** [comment]
Finally, it doesn't solve the problem...

**Comment by ninjaprox** [comment]
@stealdre: Could you provide more context of usage? (like code snippet, where using it). Since the example going the library is still working fine, the problem perhaps caused by other reason.

**Comment by pbeneteau** [comment]
I tried to use it with both ways: `storyboard` and code. I created a view (50px50px) with the class `NVActivityIndicatorView` in the `storyboard` and with animation type and color. Then I start animating with:`activityIndicatorView.startAnimating()` and stop with `activityIndicatorView.stopAnimating()`. Not working. I also tried with the second way: code. I created a `view` with: `NVActivityIndicatorView(frame: frame, type: type, color: color, padding: padding)`: not working. Same error for both ways: it makes crash the app. Then I tried the `UI blocker ` which works perfectly. I did what is written in your Usage guide.

**Comment by ninjaprox** [comment]
@stealdre: How about the following simplest use?
```swift
let aiView = NVActivityIndicatorView(frame: CGRect(x: 0, y: 0, width: 100, height: 100))

aiView.color = .black
aiView.startAnimating()
view.addSubview(aiView)
```

**Comment by pbeneteau** [comment]
This is working, try to update your guide.

**Comment by ninjaprox** [comment]
@stealdre: What's your suggestion for the better guide? PR is welcome.

**Comment by pbeneteau** [comment]
Try first to create a guide that work! The current guide is not working like I said. I did exactly what it says. Then you give me a more easy way that works. Why not put this way in your guide?

**Comment by ninjaprox** [comment]
I think it's straightforward for most people and there's no such kind of this issue before. The guide itself is not a step-by-step tutorial and may require a minimal prerequisite to understanding. Hope you understand this. 😄

**Comment by pbeneteau** [comment]
Hope people understand this...

**Comment by Oleksandr1234** [comment]
no its not, absolutely doesn't work, can't you just make it work without providing the frame? too much hassle, I tried other framework, work out of the box unlike this one
