### ISSUE TITLE
M_PI is deprecated

### ISSUE THREAD

**Issue by chris-247-sloan** [ninjaprox/NVActivityIndicatorView#128]
I've just installed NVActivityIndicatorView in my project using cocoapods. 
Podfile entry is :

![screen shot 2017-03-07 at 12 15 46](https://cloud.githubusercontent.com/assets/16673545/23656048/f4ae12e8-032f-11e7-9e1f-b7ed063f9089.png)

so I did a `pod install `

![screen shot 2017-03-07 at 12 19 59](https://cloud.githubusercontent.com/assets/16673545/23656154/6c11e616-0330-11e7-926c-5c4ef5575054.png)

and then `pod update`, which gave me 

![screen shot 2017-03-07 at 12 15 30](https://cloud.githubusercontent.com/assets/16673545/23656074/147bdbaa-0330-11e7-8fa3-ed57b6f0c0d2.png)

but i'm still getting 

![screen shot 2017-03-07 at 12 14 41](https://cloud.githubusercontent.com/assets/16673545/23656079/1f9e6372-0330-11e7-875e-04d72f2b7b2c.png)

there are 36 similar errors through out the pod.

Am I missing something from the podfile? Project is using Swift 3.0 in Xcode 8.3 Beta3.

Thanks

**Comment by ninjaprox** [comment]
@chris-247-sloan: I think it's mostly due to Xcode 8.3 Beta 3. I will update to clean all warnings when Xcode 8.3 releases officially.

**Comment by Tr736** [comment]
hi Ninjaprox,

The issue still persists on the official Xcode 8.3 release

Thanks

**Comment by rlxone** [comment]
The same on Xcode 8.3 release

**Comment by ninjaprox** [comment]
I'll update this probably over the weekend.

**Comment by ty-sang** [comment]
If you need this right way, a fork from here https://github.com/shieer/NVActivityIndicatorView

**Comment by vkornieiev** [comment]
Xcode 8.3 has been released officially. Please update version to exclude warnings ASAP.
Thank you :)

**Comment by ninjaprox** [comment]
Version `3.6.0` with fix of all warnings in Xcode 8.3 is now live 🚀. Thanks for your all patience 🙇.
