### ISSUE TITLE
Unexpected CFBundleExecutable Key

### ISSUE THREAD

**Issue by deepankvora** [ninjaprox/NVActivityIndicatorView#129]
Hi there! Thank you for this plugin. I am using it in my app and love it.

I am reaching out as I am having an issue while uploading my app to iTunes Connect. Could you please have a look at this ?

> 
> Unexpected CFBundleExecutable Key - The bundle at '/Payload/Alight.app/NVActivityIndicatorView/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.
> Once these issues have been corrected, you can then redeliver the corrected binary.
> 

Cheers,
Deepank

**Comment by ninjaprox** [comment]
@deepankvora: Does that cause app review reject? If you're using manual approach, try removing the `Info.plist`. Let me know if it helps.

**Comment by deepankvora** [comment]
Yes, it does. I am using the manual approach and removing it from `Info.plist` worked for me. Was just wondering if there could be a way to fix this so others who use it manually don't face the same issue.

**Comment by ninjaprox** [comment]
@deepankvora: I guess one way is updating the `README` to note this, then user of the library has to do it himself. Thanks for reporting this issue btw.
