### ISSUE TITLE
Message is not centered

### ISSUE THREAD

**Issue by dqhieu** [ninjaprox/NVActivityIndicatorView#132]
<img width="1072" alt="error" src="https://cloud.githubusercontent.com/assets/8291457/24284128/36e583c0-109c-11e7-9912-d86a08fa406c.png">

Please! Am I the only one getting this error?
p/s: running on iPhone 5s, iOS 10.2.1

**Comment by ninjaprox** [comment]
@dqhieu: Thanks for reporting 👍. This has been fixed in `3.5.2`.
