### ISSUE TITLE
Animating appearing / disappearing of activity indicator

### ISSUE THREAD

**Issue by mark2b** [ninjaprox/NVActivityIndicatorView#136]
Is there a way to fade in / fade out background during appearing / disappearing of activity indicator?

Now it is appearing / disappearing instantly. 

Thanks

**Comment by ninjaprox** [comment]
@mark2b: We don't have that at the moment. As always, PR is welcome.

**Comment by ninjaprox** [comment]
Available in [4.3.0](https://github.com/ninjaprox/NVActivityIndicatorView/releases/tag/4.3.0)
