### ISSUE TITLE
Replacing existing UIActivityIndicator with NVActivityIndicatorView 

### ISSUE THREAD

**Issue by pingpongdelay** [ninjaprox/NVActivityIndicatorView#139]
Hello, I have a UIActivityIndicator already set up and working on my application. The UIActivityIndicator displays on a cell while an image is loading - UITableView.

I installed the cocoa pods for NVActivityIndicatorView and have the files integrated into my project, but I am confused with how to integrate it into the current code. Whenever I replaced “@IBOutlet weak var aiView: UIActivityIndicatorView!” with “@IBOutlet weak var aiView: NVActivityIndicatorView!”, the activity indicators would not show and the app would crash.

Using Swift 3.

Thank you!

`class SubcategoryCell: UITableViewCell {
    @IBOutlet weak var subcategoryImageView: UIImageView!
    @IBOutlet weak var aiView: UIActivityIndicatorView!
}`

     func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return self.items.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "Cell") as! SubcategoryCell
        
        let item = self.items[indexPath.row]
        
        if let url = URL(string: item.url) {
            cell.aiView.startAnimating()
            cell.subcategoryImageView.kf.setImage(with: url, placeholder: nil, options: nil, progressBlock: nil, completionHandler: { (image, error, cacheType, url) in
                cell.aiView.stopAnimating()
            })
        }
        
        return cell
    }
`

**Comment by ninjaprox** [comment]
@pingpongdelay: Have you changed the class of the view in IB as well?

**Comment by pingpongdelay** [comment]
I have not, will do that now.

How would I integrate the NVActivityIndicatorView into my current code? A little confused on the implementation. 

Thank you very much.

**Comment by pingpongdelay** [comment]
I tried changing the class of the indicators I have in my project, but they don't apply (they get removed when I write them in). All three of these view controllers have activity indicators at the center.
![screen shot 2017-04-04 at 10 17 35 am](https://cloud.githubusercontent.com/assets/19244377/24669635/00ea4260-1920-11e7-8ccb-70e6a7450ace.png)

Thank you.

**Comment by ninjaprox** [comment]
@pingpongdelay: If you're using IB, make sure you have this.

![screen shot 2017-04-05 at 8 50 51 pm](https://cloud.githubusercontent.com/assets/4948012/24706242/99bdec9a-1a41-11e7-8ce7-ab3732f5b788.png)

**Comment by pingpongdelay** [comment]
Ok, will do. Would that be with the activity indicator in IB? 

Thank you very much for the help.

**Comment by pingpongdelay** [comment]
With the activity indicator selected, Xcode is not letting me change its class and module. Am I changing the class and module of the activity indicator?

Thanks for the help.

<img width="706" alt="screen shot 2017-04-05 at 9 32 33 am" src="https://cloud.githubusercontent.com/assets/19244377/24716159/e28304d8-19e2-11e7-9274-3b5db4386f8b.png">

**Comment by ninjaprox** [comment]
@pingpongdelay: Just type in those 2 text fields.

**Comment by pingpongdelay** [comment]
I try to, but they get automatically delete when I hit "enter."

![error](https://cloud.githubusercontent.com/assets/19244377/24740245/fd0a9a2e-1a54-11e7-956f-cafd7f57c84e.gif)

**Comment by pingpongdelay** [comment]
@ninjaprox I try to enter it in, but they keep getting deleted by Xcode.

![errrrrror](https://cloud.githubusercontent.com/assets/19244377/24740337/7d4c9b7e-1a55-11e7-878b-d9d280533e6f.gif)

**Comment by ninjaprox** [comment]
@pingpongdelay: It's in [README](https://github.com/ninjaprox/NVActivityIndicatorView#initialization), just recall here.

> By storyboard, changing class of any UIView to NVActivityIndicatorView.

So just remove that `UIActivityIndicatorView` in favor of `UIView` and do the above steps, it should work.

**Comment by pingpongdelay** [comment]
Works great now! The issue was that I was not creating a new UIView and setting that as "NVActivityIndicatorView".

Thank you very much for the help and thank you for this library!
