### ISSUE TITLE
Hi, NVActivityIndicatorView for Android

### ISSUE THREAD

**Issue by HarlonWang** [ninjaprox/NVActivityIndicatorView#14]
I make a library AVLoadingIndicatorView for Android like NVActivityIndicatorView,Thank you for provide such good open library. I thought I should let you know this . And I hope I don't disturb you.

https://github.com/81813780/AVLoadingIndicatorView

**Comment by ninjaprox** [comment]
:+1:

**Comment by HarlonWang** [comment]
Thanks again :)

**Comment by ninjaprox** [comment]
You're welcome :)
