### ISSUE TITLE
Fatal error: use of unimplemented initializer

### ISSUE THREAD

**Issue by LinusGeffarth** [ninjaprox/NVActivityIndicatorView#141]
I'm experiencing crashes of the @IBDesignables in Xcode 8 using NVActivityIndicatorView. The crash log shows:

`NVActivityIndicatorView.swift: 333: 20: fatal error: use of unimplemented initializer 'init(frame:) ' for class 'SOGON_TH_Denk.NVActivityIndicatorView'`

Is this known? How do I fix it?
Thanks!

**Comment by LinusGeffarth** [comment]
So after restarting Xcode a couple times & randomly debugging selected views & stuff, the error went away. There needs to be an actual fix though, since I've had that issue in several Mac's Xcodes.  

**Another update:**
I'm experiencing this problem in another Xcode project as well. Those two projects are using CocoaPods, so maybe that causes this...

**Comment by ninjaprox** [comment]
@LinusGeffarth: Could you provide more context of usage?

**Comment by LinusGeffarth** [comment]
I meant to upload the crash log. Here it comes:
[crash log.txt](https://github.com/ninjaprox/NVActivityIndicatorView/files/901623/crash.log.txt)

For usage: I create a view in storyboard, set its custom class to `NVActivityIndicatorView`, set the IBDesignables for type name & color. Then, I hook it up to my ViewController and the only code that I'm writing is `indicatorView.startAnimating()` and `indicatorView.stopAnimating()`.  
Anything else I need to do?

Otherwise, there's literally no context of the appearance of the issue at all. Suddenly it appeared. In my second project debugging selected views and refreshing all view and such doesn't even fix anything...

**Comment by ninjaprox** [comment]
@LinusGeffarth: Assure that you follow [this note](https://github.com/ninjaprox/NVActivityIndicatorView#initialization), recall here.

> _**Note:** Set Module to NVActivityIndicatorView._

**Comment by LinusGeffarth** [comment]
Yup, it is automatically set to that value.

**Comment by ninjaprox** [comment]
@LinusGeffarth: I've tried and it works fine. Are you using CocoaPods? If you're using the manual way, guarantee all files are intact.

**Comment by LinusGeffarth** [comment]
I am using CocoaPods.

**Comment by LinusGeffarth** [comment]
So I just checked (again!) whether all the modules were correct. I swear, they once were, but as I just checked, they weren't set to `NVActivityIndicatorView`. So I adjusted all of them and now its working. Apparently that's when "suddenly" the issue appeared: something broke and altered this setting.  
Thanks!

**Comment by ninjaprox** [comment]
@LinusGeffarth: Thanks for letting me know the issue has been solved 👍.
