### ISSUE TITLE
Can I apply this indicator into only one viewcontroller?

### ISSUE THREAD

**Issue by david-koch-pro** [ninjaprox/NVActivityIndicatorView#142]
I use this great indicator for my app and this indicator is applied into KeyWindow. How can I apply indicator into one view controller?

**Comment by LinusGeffarth** [comment]
Write the code inside that ViewController?!

**Comment by david-koch-pro** [comment]
Oh, sorry. I got a solution. It was creating instance of NVActivityIndicatorView and using it directly.
