### ISSUE TITLE
stopAnimating not working with WKWebView

### ISSUE THREAD

**Issue by czater** [ninjaprox/NVActivityIndicatorView#144]
So I have VC with WKWebView and I am calling . stopAnimating in didFinish but animation is still working. Also if I call . isAnimating after stop method, it returns false. What is going on? Did I missing something? Is this not compatible with WKWebView?

**Comment by ninjaprox** [comment]
@czater: Is it `stopAnimating()` of `NVActivityIndicatorView` or `NVActivityIndicatorPresenter`?

**Comment by czater** [comment]
@ninjaprox of NVActivityIndicatorView

**Comment by ninjaprox** [comment]
@czater: I believe you don't miss anything and it has nothing to do with `WKWebView`. Could you provide some codes for inspecting though?

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
