### ISSUE TITLE
Prebuilt Binaries - Carthage

### ISSUE THREAD

**Issue by jwelton** [ninjaprox/NVActivityIndicatorView#145]
### Issue Description
Submit prebuilt binaries with releases to improve CI performance when using Carthage.

#### What
I think it would be really useful to include Carthage prebuilt binaries with releases. This means when using Carthage, the binary can be downloaded rather than needing to recompile the entire library. This enhancement would be much appreciated when running CI builds, as currently some of the largest time for a project can be taken with building dependencies.

**Comment by ninjaprox** [comment]
@jwelton: How about check in `Carthage/Build` folder to SVC? I think it's perhaps one alternative solution you might use outright.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
