### ISSUE TITLE
Background Image and Transition Animation

### ISSUE THREAD

**Issue by douglas-srs** [ninjaprox/NVActivityIndicatorView#146]
Hey there,

Can I suggest that you implement a way to set a background image instead of just setting the background color? Also, a way to animate the view transition would be awesome!

Thanks for this library, it helps me a lot!

**Comment by ninjaprox** [comment]
@douglas-srs: I think #137 is addressing your suggestion, however it doesn't support background image. As always, PR is welcome.

**Comment by ninjaprox** [comment]
Close and merge to #136, the requests are almost the same, except this one requests additional background image.
