### ISSUE TITLE
pull to refresh support?

### ISSUE THREAD

**Issue by calvinsug** [ninjaprox/NVActivityIndicatorView#148]
Hi, just want to know whether this library supports pull to refresh ?

**Comment by ninjaprox** [comment]
@calvinsug: You can use this library in conjunction with other pull-to-refresh libraries since the `NVActivityIndicatorView` is just a subclass of `UIView`, you can use it anywhere.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
