### ISSUE TITLE
carthage support error

### ISSUE THREAD

**Issue by JonFir** [ninjaprox/NVActivityIndicatorView#15]
Hello! I add your library with carthage, but now my project not archived with reason:

ld: bitcode bundle could not be generated because '/Users/tygeddar/mobile_aplication/Pintv/Carthage/Build/iOS/NVActivityIndicatorView.framework/NVActivityIndicatorView' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture armv7

**Comment by ninjaprox** [comment]
Which Carthage version are you using? I found this release note [0.9.4](https://github.com/Carthage/Carthage/releases/tag/0.9.4). It seems this issue has been resolved in latest Carthage version.

**Comment by JonFir** [comment]
Hello.
Rly, after update Carthage to last version issue was ended. curiously what all other library work fine in 0.9.4 version. But sorry for interrupting and thank you for fast answer!

**Comment by ninjaprox** [comment]
You're welcome :)
