### ISSUE TITLE
NVActivityIndicatorView doesn't work on iPad

### ISSUE THREAD

**Issue by luli-isa** [ninjaprox/NVActivityIndicatorView#150]
Hi, 
I am used NVActivityIndicatorView and it works on iPhone (and on iPad simulator), but when I try on iPad it doesn't show.
Why does it have this behaviour?
Thanks

**Comment by ninjaprox** [comment]
@luli-isa: Which version are you using?

**Comment by luli-isa** [comment]
I am trying the version on master
`pod 'NVActivityIndicatorView'`

**Comment by ninjaprox** [comment]
@luli-isa: I tried the demo project on my iPad and it worked just fine. Could you try the same and let me know the result?

**Comment by ninjaprox** [comment]
Close this, reopen if need be.

**Comment by Nidhi126nj** [comment]
@ninjaprox 
It works on iPad but code crash when we take screenshot of screen. Any suggestions ?

error:- 
The view hierarchy is not prepared for the constraint: <NSLayoutConstraint:0x2800e2940 BGSInfoWindow:0x108000a20.leading == UIView:0x10343fc50.leading   (inactive)>
