### ISSUE TITLE
how to know if it is already showing the indicator view?

### ISSUE THREAD

**Issue by iad24** [ninjaprox/NVActivityIndicatorView#152]
I dont see any isHidden property.

**Comment by ninjaprox** [comment]
@iad24: You can use [`isAnimating`](http://cocoadocs.org/docsets/NVActivityIndicatorView/3.6.1/Classes/NVActivityIndicatorView.html#/s:vC23NVActivityIndicatorView23NVActivityIndicatorView11isAnimatingSb).

**Comment by iad24** [comment]
thanks

**Comment by iad24** [comment]
@ninjaprox  Oppps. But how to access this? Its not exposed to NVActivityIndicatorPresenter
