### ISSUE TITLE
 error: filename "AppDelegate.swift" used twice

### ISSUE THREAD

**Issue by dfabreguette** [ninjaprox/NVActivityIndicatorView#154]
Hi,
I'm getting this build error when I included the pod via cocoaPod :
```
<unknown>:0: error: filename "AppDelegate.swift" used twice: '/Users/davidfabreguette/Sites/mobile/mobile/NVActivityIndicatorView/Example/NVActivityIndicatorViewExample/AppDelegate.swift' and '/Users/davidfabreguette/Sites/mobile/mobile/AppDelegate.swift'
<unknown>:0: note: filenames are used to distinguish private declarations with the same name
```
Any Idea ?

**Comment by ninjaprox** [comment]
@dfabreguette-ap: I tried with a new clean project and it's fine. Could you try `pod deintegrate`, then `pod install` again?

**Comment by dfabreguette** [comment]
I tried to deintegrate but I get the same error.
I'm using IOS10 could it be related to it ?

**Comment by dfabreguette** [comment]
Also, when I add the import directive, I get the following :
```
no such module NVActivityIndicatorView
```
![image](https://user-images.githubusercontent.com/7055931/28072530-a3f8cb86-6653-11e7-8bdd-d064f17c0c66.png)

**Comment by ninjaprox** [comment]
@dfabreguette-ap: I also tried using iOS 10. How about a try with version `3.6.1`? I'm suspecting the recent change in `podspec` might cause this.

**Comment by dfabreguette** [comment]
For some reasons, my cocoapod install was messing up the whole thing !
I followed these steps to uninstall / reinstall cocoapods and finally worked fine !
https://stackoverflow.com/a/32757139

Be sure to open xcworkspace file and not xcodeproj with xcode to build properly !
