### ISSUE TITLE
Enable Loading with blocking only on viewcontroller.view 

### ISSUE THREAD

**Issue by Ankish** [ninjaprox/NVActivityIndicatorView#156]
Enable Loading with blocking only on viewcontroller.view and not the whole screens. This way navigation bar is not blocked and use can still change screens. How do we achieve that in a simple way ?

**Comment by ninjaprox** [comment]
@Ankish: You might want to check related issue #155.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
