### ISSUE TITLE
Loading Indicator doesn't always show

### ISSUE THREAD

**Issue by alexn-ai** [ninjaprox/NVActivityIndicatorView#157]
Using the shared instance to display the loading indicator inside a background thread initiating a network request, there are instances where it does not show.  It's infrequent, and occurs about 1:20 times from testing.  

`  let activityData = ActivityData()
        NVActivityIndicatorPresenter.sharedInstance.startAnimating(activityData)`

I use the current settings:
`        NVActivityIndicatorView.DEFAULT_BLOCKER_DISPLAY_TIME_THRESHOLD = 0
        NVActivityIndicatorView.DEFAULT_BLOCKER_MINIMUM_DISPLAY_TIME = 200
        NVActivityIndicatorView.DEFAULT_TYPE = .lineSpinFadeLoader
        NVActivityIndicatorView.DEFAULT_BLOCKER_SIZE = CGSize(width: 30, height: 30)
        NVActivityIndicatorView.DEFAULT_BLOCKER_MESSAGE = "Loading..."
        NVActivityIndicatorView.DEFAULT_BLOCKER_MESSAGE_FONT = AIUIConstants.Font.semiBold(size: 20.0)`

**Comment by ninjaprox** [comment]
@alexn-spire: If I get it correctly, you call `startAnimating()` in a thread other than the main thread? Besides, according to the setting, ensure that a subsequent call to `startAnimating()` is 200 ms after the previous one, otherwise, it'll be ignored.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
