### ISSUE TITLE
Allow adjusting Type, Color, Size from Code

### ISSUE THREAD

**Issue by winkelsdorf** [ninjaprox/NVActivityIndicatorView#16]
Hi,

just tried to use this from a Storyboard. Would be great to be able to set the above values in code before calling startAnimation() ;)

Creating a PR for it..

Cheers

**Comment by winkelsdorf** [comment]
PR #17

And yes, I saw the delegate. But that's a bit oversize if you just want to set the color before calling startAnimation().

**Comment by ninjaprox** [comment]
Nice point :+1:. Merged.

**Comment by winkelsdorf** [comment]
You're welcome! Thanks for the component and merging :)
