### ISSUE TITLE
NVActivityIndicatorView hanging after UIViewController transition

### ISSUE THREAD

**Issue by WilliamHua** [ninjaprox/NVActivityIndicatorView#160]
Hi,

I am using NVActivityIndicatorView during my network requests as a loading indicator. 

Specifically, I am adding the NVActivityIndicatorView the another view, laying it out with AutoLayout, and then presenting it by adding the view to the app's Window. 

I recently added an animation library called [Hero](https://github.com/lkzhao/Hero). 

After I started using Hero, NVActivityIndicatorView started hanging. For example, I am using the "lineScalePulseOut" animation, and the animation will not begin animating, and all the user will see is 5 bars at the same height standing still. After a few seconds, the animation will begin.

If no Hero animations are triggered throughout the usage of the app, the NVActivityIndicatorView does not hang. the moment a Hero animation is triggered, the NVActivityIndicatorView begins hanging for a (very) short period of time (<1s). 

However, the more Hero animations are used, the more there is hanging.

I have attempted to switch out Hero with [Motion](https://github.com/CosmicMind/Motion), a library that does the same thing, and the same hanging effect occurs.

Do you know where I should look to start debugging this issue?

**Comment by ninjaprox** [comment]
@WilliamHua: Is `NVActivityIndicatorView ` a part of the animation performed by either Hello or Motion? Screenshots might help to visualize the scenario.

**Comment by WilliamHua** [comment]
No, `NVActvitiyIndicatorView` is not related to the animation performed and is not called until the user goes to a completely different part of the app. However, there is a reference to a `NVActivityIndicatorView` in one of the `UIViewController`'s. 

To elaborate, I have 3 `UIViewController`'s: A, B, C.

A: has a reference to `NVActivityIndicatorView`
B: has no reference
C: has a reference to a different `NVActivityIndicatorView`

The animation using the two libraries (`Hero` / `Motion`) occurs when transitioning from A -> B, AND from B <- A. If the user ever goes to C, or refreshes the screen on A, the `NVActivityIndicatorView` seems to hang. 

I can provide a screenshot if you'd like, but wouldn't it just be a picture of the `NVActivityIndicatorView`? I may be incorrectly understanding something. 


I am not sure if this is relevant, but I have temporarily alleviated the problem by using another loading animation library. I can link it here if you'd like.

**Comment by ninjaprox** [comment]
@WilliamHua: Well when is `NVActivityIndicatorView` being displayed or used? And how in conjunction with Hero and Motion. As you described earlier, I quite understand you're using `NVActivityIndicatorView` as a UI blocker. If it's correct, I'm assuming that while the UI blocker is displaying (with `NVActivityIndicatorView` in it), there's transition from A -> B using either Hero or Motion. The link to the other library would be nice, I can have a look at its implementation and improve `NVActivityIndicatorView`.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
