### ISSUE TITLE
Error while compiling with Swift 4

### ISSUE THREAD

**Issue by wstyres** [ninjaprox/NVActivityIndicatorView#162]
I just updated my project to Swift 4 and Xcode 9 beta and I'm getting the following error while trying to build:

```
NVActivityIndicatorViewable.swift:53:12: error: only classes and class members may be marked with 'final'
    public final func startAnimating(
           ^~~~~~
           
NVActivityIndicatorViewable.swift:81:12: error: only classes and class members may be marked with 'final'
    public final func stopAnimating() {
           ^~~~~~
```

Works fine if I unlock the file and remove the `final` but it would be nice if the pod were updated so I don't get build errors with travis.

**Comment by awedeebawe** [comment]
Why don't you fork it, update it, set your Podfile to use your repo and create a pull request, that ninjaprox will approve when the time has come?

**Comment by ninjaprox** [comment]
@wstyres: At the moment, you can specify the pod to use `swift4` branch. Once Xcode 9 releases officially there'll be a new appropriate version of the pod.

**Comment by wstyres** [comment]
@ninjaprox awesome that will work for the time being, thank you!
