### ISSUE TITLE
animator not displayed in viewdidload

### ISSUE THREAD

**Issue by bhaveshbc** [ninjaprox/NVActivityIndicatorView#166]

**Comment by bhaveshbc** [comment]
```swift
startAnimating(size, message: "", type: NVActivityIndicatorType(rawValue: NORMAL_SPINNER)!, color: THEME_COLOR,  backgroundColor: UIColor.white.withAlphaComponent(0.5))
```

I have Placed above code in viewdidload method of viewcontroller but indicator not displayd.

**Comment by ninjaprox** [comment]
@bhaveshbc: What is the color of `THEME_COLOR`? Another thing is when `stopAnimating` is called?

**Comment by kohdesmond** [comment]
@ninjaprox i'm experiencing that too

**Comment by ninjaprox** [comment]
@kohdesmond: I tried with a simple setup in the example project as the following:

```swift
override func viewDidLoad() {
        super.viewDidLoad()

        startAnimating(CGSize(width: 80, height: 80), message: "", type: NVActivityIndicatorType(rawValue: 1)!, color: .red,  backgroundColor: UIColor.white.withAlphaComponent(0.5))
```

However, I know it seems too simple to reproduce the issue. An example with reproducible issue would be helpful to debug.

**Comment by kohdesmond** [comment]
@ninjaprox thanks, i'm running 2 project and one of it with tabbar works fine.
 the one i'm encountering issues was running with 
`pod 'SideMenu'` as the slide menu, putting a delay seems to fix the issues
