### ISSUE TITLE
Doesn't work with swift 4?

### ISSUE THREAD

**Issue by julienfouilhe** [ninjaprox/NVActivityIndicatorView#167]
I'm getting the following errors when trying to compile with swift 4.

```
Only classes and class members may be marked with final
```

It happens on NVIndicatorViewable.swift for `startAnimating` and `stopAnimating`

cc @ninjaprox 

Edit: Just noticed that a swift branch was available, using this until it's merged :)

**Comment by ninjaprox** [comment]
@julienfouilhe: The version `4.0.0` is out 🚀, let's check it 🎉.
