### ISSUE TITLE
Swift 4 error Only classes and class members may be marked with 'final'

### ISSUE THREAD

**Issue by matin-kaj** [ninjaprox/NVActivityIndicatorView#168]
I am getting this error when I migrated to swift 4. I also ran pod install again to grab the version for swift 4.

    public final func startAnimating

**Comment by ninjaprox** [comment]
@matin-kaj: Which version are you using? If not `4.0.0` (make sure you check the version in `Podfile.lock`), check it out since it's updated with Swift 4. Let me know if it helps.

**Comment by matin-kaj** [comment]
When I replace `pod 'NVActivityIndicatorView'` with `pod 'NVActivityIndicatorView', '~> 4.0.0' `and run pod install again, it can't find it. any idea ?

**Comment by petard** [comment]
Running ```pod repo update``` fixed the issue for me using ```pod 'NVActivityIndicatorView', '~> 4.0.0```

**Comment by ninjaprox** [comment]
@matin-kaj: You might need to run `pod install` or `pod update NVActivityIndicatorView` with `--repo-update` option to update the pod specs repo in your local.
