### ISSUE TITLE
Unexpected Warning

### ISSUE THREAD

**Issue by prajapatirukesh3c** [ninjaprox/NVActivityIndicatorView#170]
Warning: This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes.

Xcode version 8.3.3
swift version 3

**Comment by seenoevo** [comment]
Wrap the code around this:

    DispatchQueue.main.async() {
 
        // Put indicator code here
   
    }
