### ISSUE TITLE
Stop animation not working

### ISSUE THREAD

**Issue by andresteves** [ninjaprox/NVActivityIndicatorView#171]
Hi,

Trying to use
`NVActivityIndicatorPresenter.sharedInstance.stopAnimating()` with a Timer but nothing happens and the UI is still blocked...

**Comment by ninjaprox** [comment]
@andresteves: Could you give more context? Code snippets are also helpful.

**Comment by andresteves** [comment]
Ended up not being the framework fault. I had a code running that was not async so it was blocking everything.
