### ISSUE TITLE
Fast show/hide calls

### ISSUE THREAD

**Issue by piv199** [ninjaprox/NVActivityIndicatorView#173]
Hi, I've experienced a strange bug, couldd you please give your ideas on it:

```
startAnimating(displayTimeThreshold: 500) //500ms async delay
stopAnimating()
startAnimating(displayTimeThreshold: 500) //will not be shown
// 3seconds delay
stopAnimating()
```

In underlying start/stop implementation, I've faced this method:

```
    private func _hide() {
        if state == .waitingToHide {
            hide()
        } else if state != .hidden {
            state = .waitingToHide //called at stop animating(), because the current state .waitingToShow
        }
    }
```

But `state = .waitingToHide` doesn't actually hide the hud, and when calling any startAnimating after that it won't be shown because of 
```
    public final func startAnimating(_ data: ActivityData) {
        guard state == .hidden else { return }
```

Do I missing something?

@ninjaprox

**Comment by ninjaprox** [comment]
@piv199: For the idea behind `displayTimeThreshold`, you can refer to the issue #57. In brief, if you call `stopAnimating()` in `displayTimeThreshold` time window, no thing will be showed, and the `state` is to keep the internal state of the hub. If you find a leaner way to manage the state, feel free to propose and create PR.

**Comment by piv199** [comment]
yeah, but if I call sartAnimating() after stopAnimating() it won't show, will it?

Okay, I will take a look in more details, and try to create a pr.

**Comment by piv199** [comment]
@ninjaprox if you call `stopAnimating()` in `displayTimeThreshold`, then the state will be forever .waitingToHide, until you call `stopAnimating()` again.

This is major bug, and I'm thinking of it... But I'm bit confused of state machine behavior... so if I'm `.waitingToShow` and call `startAnimating(displayTimeThreshold: 1000)`. Should HUD be shown after 1000 ms from now, or after first call to `startAnimating()` which caused `.waitingToShow` state?

**Comment by ninjaprox** [comment]
@piv199: #180 seems related to this, and fixed by #181. Could you have a look?

**Comment by ninjaprox** [comment]
Close this, reopen if need be.

**Comment by piv199** [comment]
@ninjaprox yeah, it's fixed, but I've forgotten to mention it here. 
Thanks so much!

However, the code structure is a bit strange, and perhaps state machine pattern would fit much better for activity indicator work)
