### ISSUE TITLE
NVActivityIndicatorPresenter blocking only UIViewController

### ISSUE THREAD

**Issue by Skornos** [ninjaprox/NVActivityIndicatorView#174]
Hi,

I love this indicator view. The only issue I have is that starting animation with `NVActivityIndicatorPresenter.sharedInstance` blocks the whole UI including navigation controller and tab bar. I am looking for a solution how to create in some reusable fashion NVActivityIndicatorView which will block only presenting ViewController. 

Thanks.

**Comment by annjawn** [comment]
I think if you create a UIView as a subclass of NVActivityIndicatorView and then use it will only block that UIView. I think I saw something like that in the sample project. You may want to double check that.

**Comment by sheinix** [comment]
You could declare a NVActivityIndicatorView inside your ViewController and change the frame to fit your UI element, and then encapsulate the implementation that shows the loading view. Something like this:

In your presenting ViewController or parent class:

 ```
override func viewDidLoad() {
        super.viewDidLoad()
        let originX = UIScreen.main.bounds.width/2
        let originY = UIScreen.main.bounds.height/2
        let frame = CGRect(x: originX-(Loader.loaderViewSize.width/2), y: originY-(Loader.loaderViewSize.height), width: Loader.loaderViewSize.width, height: Loader.loaderViewSize.height)
        loadingView = NVActivityIndicatorView(frame: frame, type: NVActivityIndicatorType.ballPulse, color: UIColor.Palette.violetMain)
        loadingView?.tag = Loader.loaderID
    }
    
    public func showLoadingView() {
        // block the UI: 
        UIApplication.shared.beginIgnoringInteractionEvents() 
        guard let view = self.view.subviews.filter({ $0.tag == Loader.loaderID }).first else {
            self.view.addSubview(self.loadingView!)
            self.view.bringSubview(toFront: self.loadingView!)
            self.loadingView?.startAnimating()
            return
        }
        if let loader = view as? NVActivityIndicatorView {
            loader.startAnimating()
        }
        
    }
    public func stopLoadingVIew() {
        // accept user interaction again:
        UIApplication.shared.endIgnoringInteractionEvents()
        loadingView?.stopAnimating()
    }
```

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
