### ISSUE TITLE
Callback/Delegate for stopAnimating()

### ISSUE THREAD

**Issue by annjawn** [ninjaprox/NVActivityIndicatorView#175]
Is there a callback/delegation available for `stopAnimating()`? If not then it would be a really useful feature since it looks like the `stopAnimating()` is somewhat asynchronous. I see the activity view lingering for a slightly longer period as the code after the `stopAnimating()` gets executed (for e.g. present another VC, Push/pop another VC, show an alert etc.). Not a huge issue, but it would give a consistent UI behavior for the user.

**Comment by ninjaprox** [comment]
@annjawn: So far there's no callback from `stopAnimating()`. The display prolonging is because of `minimumDisplayTime`, setting it to 0 might help.

**Comment by annjawn** [comment]
@ninjaprox yes, it was the minimumDisplayTime value that was causing it. Thanks.
