### ISSUE TITLE
Add identifier to NVActivityIndicatorView

### ISSUE THREAD

**Issue by LinusGeffarth** [ninjaprox/NVActivityIndicatorView#177]
Thanks for this amazing library.
I have a simple feature request: add an identifier to the `NVActivityIndicatorView` class:
```
/// Identifier of activity indicator view
@IBInspectable public var id: String?
```

Thanks!

**Comment by ninjaprox** [comment]
@LinusGeffarth: I wonder what is the usage of this since if you want an identifier, `UIView.tag` might do the job.

**Comment by LinusGeffarth** [comment]
If you have multiple activity indicators in one view controller, you wouldn't have to hook each of them up with an `@IBOutlet` but could access them via their id instead.  
Maybe that's too specific to my project, though.
