### ISSUE TITLE
Add new animations?

### ISSUE THREAD

**Issue by ParkGwangBeom** [ninjaprox/NVActivityIndicatorView#179]
I have a question. Can I pull requests by adding another type of indicator to this open source?

**Comment by ninjaprox** [comment]
@ParkGwangBeom: Sure, it's alway welcome. However, please make sure the animation is fitted in the box, you can refer to existing animations for detail.

**Comment by ParkGwangBeom** [comment]
@ninjaprox Add circle stroke animation #184

**Comment by ninjaprox** [comment]
@ParkGwangBeom: Thanks for the new animation 👍
