### ISSUE TITLE
Failable initialiser cannot override a non-bailable initializer

### ISSUE THREAD

**Issue by colasbd** [ninjaprox/NVActivityIndicatorView#18]
![capture d ecran 2015-11-22 a 16 24 05](https://cloud.githubusercontent.com/assets/4303814/11326357/7bc17644-9135-11e5-862f-50bbcea214ca.png)

**Comment by ninjaprox** [comment]
Did you compile from drop-in source code or CocoaPods?
I've checked to compile source code itself, it've gone well.

**Comment by colasbd** [comment]
Yes, from CocoaPods. Finally, I don't use your library.

**Comment by ninjaprox** [comment]
Which Swift version are you using? I've also tested from CocoaPods with latest Swift version, everything is fine.

**Comment by colasbd** [comment]
I have two versions of Xcode : 6.4 and 7 (and I use both of them)

Maybe I opened the project with 6.4 !! Can't be sure it was 7.0.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
