### ISSUE TITLE
Unable to use via cocoapods

### ISSUE THREAD

**Issue by grosch** [ninjaprox/NVActivityIndicatorView#182]
I added this to my podfile and ran install and it says "Using NVActivityIndicatorView (3.6.1)".  Your README seems to imply it should be a 4.x version.

When I open the workspace I get errors about functions being marked as final.

**Comment by ninjaprox** [comment]
@grosch: Which Swift version are you using?

**Comment by grosch** [comment]
4.  Not sure what happened but the next time i ran an install it put in a version that worked.

**Comment by MatrixSenpai** [comment]
Hey @grosch,
Sometimes dependencies aren't always up-to-date with the latest standards, some stuff may have changed in Swift 4.1 -> 4.2

You can assign the Swift Build Version in CocoaPods by setting the build version in the post_installation hook. Here's an example:
```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if['NVActivityIndicatorView', 'MyOtherAwesomePod'].include? t.name
      t.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
end
```
Look out for my upcoming article explaining the how/why on [CodeMentor](https://codementor.io/matrixsenpai)! :)
