### ISSUE TITLE
cannot find circleStrokeSpin

### ISSUE THREAD

**Issue by rami965** [ninjaprox/NVActivityIndicatorView#186]
'circleStrokeSpin' cannot be found on the list 
![screen shot 2017-12-11 at 10 15 01 am](https://user-images.githubusercontent.com/20938033/33821358-3223d998-de5c-11e7-9031-40b5067f9b3a.png)

**Comment by rami965** [comment]
how to include it, please ?

**Comment by alickbass** [comment]
You can use my fork. If you use Carthage, you can do it with: `github "alickbass/NVActivityIndicatorView" "fix-build-circle-stroke-spin"`

**Comment by rami965** [comment]
Thank you
