### ISSUE TITLE
Carthage build error

### ISSUE THREAD

**Issue by maclacerda** [ninjaprox/NVActivityIndicatorView#189]
Hello,

I have an issue on executing carthage command to add your library on my project, see the message below:

`
*** Building scheme "NVActivityIndicatorViewAppExtension" in NVActivityIndicatorView.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/marcoslacerda/my-project/Carthage/Checkouts/NVActivityIndicatorView/NVActivityIndicatorView/NVActivityIndicatorView.xcodeproj -scheme NVActivityIndicatorViewAppExtension -configuration Release -derivedDataPath /Users/marcoslacerda/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/NVActivityIndicatorView/4.1.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/_c/3nj34dfs13qb1ny20c_g06qm0000gn/T/NVActivityIndicatorView SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/marcoslacerda/my-project/Carthage/Checkouts/NVActivityIndicatorView)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/_c/3nj34dfs13qb1ny20c_g06qm0000gn/T/carthage-xcodebuild.L1CU2i.log
`

This is a part the content of log file:

`
/Carthage/Checkouts/NVActivityIndicatorView/NVActivityIndicatorView/NVActivityIndicatorView/NVActivityIndicatorView.swift:336:20: error: use of unresolved identifier 'NVActivityIndicatorAnimationCircleStrokeSpin'
            return NVActivityIndicatorAnimationCircleStrokeSpin()
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

** ARCHIVE FAILED **

The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal arm64
(2 failures)
`

Do you have any idea of this issue?

Thanks for your help

[UPDATE]

If i use the version 3.7.0 the problem not occurred

=D

**Comment by alexn-ai** [comment]
I see the same thing.

Xcode 9.2, High Sierra

**Comment by ninjaprox** [comment]
@marcoslacerda: It seems related to #186, and the fix in #187 has been merged to `master`. Could you check again?

**Comment by maclacerda** [comment]
@ninjaprox Thank you for your help

But the problem persist yet.

If i use the code below in my Carthage file the error on build occurred:

`github "alickbass/NVActivityIndicatorView"`

If i use the code on #186 the problem not occurred.

Do you have Any idea ?

Thanks

**Comment by ninjaprox** [comment]
@marcoslacerda: Please refer to [`Cartfile` spec](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#example-cartfile). By using either `github "ninjaprox/NVActivityIndicatorView"` or `github "alickbass/NVActivityIndicatorView"`, it refers to the latest version `4.1.0` which's having the issue. At the moment, you can fix this by specifying the branch `github "ninjaprox/NVActivityIndicatorView" "master"`. I'll release a new version with the fix by today.

**Comment by maclacerda** [comment]
Ok

I'm using :

`github "ninjaprox/NVActivityIndicatorView"`

In my Cartfile, i'll wait for your release, thank you!

**Comment by ninjaprox** [comment]
@marcoslacerda: `4.1.1` is out 🚀 . Please help check.

**Comment by alexn-ai** [comment]
@ninjaprox As for me, the latest version 4.1.1 builds fine in Carthage now.  Thank you!

**Comment by maclacerda** [comment]
I'm sorry for the delay in returning.

Version 4.1.1 is working perfectly with Carthage now, thanks for the support.

Thanks
