### ISSUE TITLE
How do I change the loading type when I am using ActivityData() ?

### ISSUE THREAD

**Issue by junweimah** [ninjaprox/NVActivityIndicatorView#190]
I want to call this animation with one lines of code from anywhere of my project. So I have created a Util.swift, and make 2 functions. Like this : 

```
func showLoading(message: String){
    let activityData = ActivityData()

    NVActivityIndicatorPresenter.sharedInstance.startAnimating(activityData)
    NVActivityIndicatorPresenter.sharedInstance.setMessage(message)
}

func hideLoading(){
    NVActivityIndicatorPresenter.sharedInstance.stopAnimating()
}
```

So I can successfully show the loading by calling 

`showLoading(message: "Testing loading util...")`

But the animation is showing .ballSpinFadeLoader, which is not I want.

How to I change the animation type?

**Comment by ninjaprox** [comment]
@junweimah: You can do it by changing the global default value `NVActivityIndicatorView.DEFAULT_TYPE` to another animation type, or pass the type on initializing `ActivityData(type: <type>)`.
