### ISSUE TITLE
Message without UI Blocker?

### ISSUE THREAD

**Issue by annjawn** [ninjaprox/NVActivityIndicatorView#191]
Is it possible to add a message the the indicator view without implementing UI Blocker? I can't seem to find a way to do it.

**Comment by ninjaprox** [comment]
@annjawn: It's not an out-of-the-box feature, however you still can create a custom `UIView` including a `NVActivityIndicatorView` and a `UILabel` to achieve the same result.

**Comment by annjawn** [comment]
@ninjaprox thanks, that's how I have been doing it but then I am also having to handle the hiding and showing of the label separately since `stopAnimating()` will just hide the indicator. Yes, its a desirable feature. But excellent library I ❤️ it. 😊

**Comment by makeitTim** [comment]
I also need this feature. A Loading Indicator the user should be able to cancel if they give up.

Thanks for the library!

**Comment by annjawn** [comment]
@makeitTim I ended up creating a small uiview xib file with the indicator and a UILabel on it. And I have been using that for non-blocking scenarios.

**Comment by bogdan-razvan** [comment]
@annjawn care to share your solution?

**Comment by annjawn** [comment]
I have a custom `UIView` xib which has another `UIView` of class `NVActivityIndicatorView` and a `UILabel` below it. Set the type of indicator using property pallet, and color-

![image](https://user-images.githubusercontent.com/26977294/40047108-70c7e62a-57e3-11e8-9edb-b0e3b1b3e557.png)


here's what the custom `UIView` class looks like-

```
import UIKit
import NVActivityIndicatorView

class CustomActivityView: UIView {

    @IBOutlet weak var activityView: NVActivityIndicatorView!
    @IBOutlet weak var activityTitle: UILabel!
    
    class func instanceFromNib() -> CustomActivityView {
        return UINib(nibName: "CustomActivityView", bundle: nil).instantiate(withOwner: nil, options: nil)[0] as! CustomActivityView
    }

}
```

Usage -

```
let view = CustomActivityView.instanceFromNib()
view.frame = CGRect(x: 0, y: 0, width: 100 , height: 90) //or whatever size works for you
view.activityTitle.text = "Please Wait..."       //or whatever text works for you
superView.addSubview(view)
view.activityView.startAnimating()
...
...
...
//Loading is done, stop animation and remove
view.activityView.stopAnimating()
view.removeFromSuperview()
```

**Comment by BakhtiyarHussain** [comment]
how to 

> I have a custom `UIView` xib which has another `UIView` of class `NVActivityIndicatorView` and a `UILabel` below it. Set the type of indicator using property pallet, and color-
> 
> ![image](https://user-images.githubusercontent.com/26977294/40047108-70c7e62a-57e3-11e8-9edb-b0e3b1b3e557.png)
> 
> here's what the custom `UIView` class looks like-
> 
> ```
> import UIKit
> import NVActivityIndicatorView
> 
> class CustomActivityView: UIView {
> 
>     @IBOutlet weak var activityView: NVActivityIndicatorView!
>     @IBOutlet weak var activityTitle: UILabel!
>     
>     class func instanceFromNib() -> CustomActivityView {
>         return UINib(nibName: "CustomActivityView", bundle: nil).instantiate(withOwner: nil, options: nil)[0] as! CustomActivityView
>     }
> 
> }
> ```
> Usage -
> 
> ```
> let view = CustomActivityView.instanceFromNib()
> view.frame = CGRect(x: 0, y: 0, width: 100 , height: 90) //or whatever size works for you
> view.activityTitle.text = "Please Wait..."       //or whatever text works for you
> superView.addSubview(view)
> view.activityView.startAnimating()
> ...
> ...
> ...
> //Loading is done, stop animation and remove
> view.activityView.stopAnimating()
> view.removeFromSuperview()
> ```

i want to use your way and also want to block ui how ?

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
