### ISSUE TITLE
Add facebook loading animation

### ISSUE THREAD

**Issue by nhatquangz** [ninjaprox/NVActivityIndicatorView#195]
Great lib 👍  I use it already :))
I very like facebook loading indicator, so please add it to your lib. And i hope to see soon a way to add custom animation :))
Other, i think support successfully (or failed) icon after hide is very usefull feature.
![facebook-loading](https://user-images.githubusercontent.com/20753825/35195182-3821144e-fef2-11e7-9191-27c589830ff7.jpg)

Thanks

**Comment by ninjaprox** [comment]
Thanks for your interest. I don't plan to add new animations soon so I'll close this, for now.
