### ISSUE TITLE
'shared' is unavailable: Use view controller based solutions where appropriate instead.

### ISSUE THREAD

**Issue by cdiclemente** [ninjaprox/NVActivityIndicatorView#196]
The line:
guard let keyWindow = UIApplication.shared.keyWindow else { return }

in the file NVActivityIndicatorPresenter.swift is giving me the error of " 'shared' is unavailable: Use view controller based solutions where appropriate instead."

How can I get around this/fix this ?

**Comment by ninjaprox** [comment]
@cdiclemente: If you're using the library in app extension, please use `NVActivityIndicatorView/AppExtension` instead. Refer to [Migration](https://github.com/ninjaprox/NVActivityIndicatorView#version-370) and #202.
