### ISSUE TITLE
Custom Animation

### ISSUE THREAD

**Issue by tevghenii-zz** [ninjaprox/NVActivityIndicatorView#199]
Hey guys!

I would like to use the library with the custom animation. Is it doable?
I checkout the `custom-animations` branch but it is outdated, we use xcode 9 and swift 4.

Thanks for your lib, is great!

**Comment by ninjaprox** [comment]
@tevghenii: It's been abandoned for a long time, you can check the discussion in #39. Recently, there's the PR #203 regarding this, but no progress so far.

**Comment by jdrevet** [comment]
It would be a useful feature.
@ninjaprox What is missing to accept the PR #203 ? I can help if needed ...

**Comment by ninjaprox** [comment]
@jdrevet: It's quite outdated now. Could you help rebase to the latest code, run through SwiftLint and update documentation for it? Beside, if you come up with any better ideas, they're welcome.

**Comment by ninjaprox** [comment]
Close this with my opinion regarding customization at https://github.com/ninjaprox/NVActivityIndicatorView/issues/267#issuecomment-467465790
