### ISSUE TITLE
Cannot change ActivityData properties

### ISSUE THREAD

**Issue by siempay** [ninjaprox/NVActivityIndicatorView#200]
I dont know why there is no way to do something like this : 
`		let activityData = ActivityData(); 
activityData.color = myColor;`

If I wanna override one of the attributes, I will have to deal with big `init`! 
why I can"t just create an instance and then override what ever I want?

**Comment by ninjaprox** [comment]
@siempay: You can in fact, `let activityData = ActivityData(color: myColor)`. However you can't change properties after init, since they're all private.
