### ISSUE TITLE
Item 32 - CircleStrokeSpin - Not found

### ISSUE THREAD

**Issue by paulocoutinhox** [ninjaprox/NVActivityIndicatorView#201]
Hi,

Im getting error when try use: Item 32 - CircleStrokeSpin.

Can anyone help me?

Thanks.

**Comment by emildzwonek** [comment]
Just update the package - problem solved.

**Comment by ninjaprox** [comment]
@prsolucoes: This has been fixed, please refer to #185, #186 and #189.
