### ISSUE TITLE
Checking isAnimating using NVActivityIndicatorViewable?

### ISSUE THREAD

**Issue by jessicae5** [ninjaprox/NVActivityIndicatorView#204]
Hi, I'm using NVActivityIndicatorViewable (e.g. calling startAnimating() on the entire UIViewController) and was wondering if there's a way to check if it's currently in animation. Thank you for letting me know!

**Comment by ninjaprox** [comment]
@jessicae5: Unfortunately, no way for now. However, this might be a feature request and added in future.

**Comment by ninjaprox** [comment]
@jessicae5: It's now available on `4.2.0` 🚀, please check it out.
