### ISSUE TITLE
Cannot view activity indicator after adding it in storyboard view controller

### ISSUE THREAD

**Issue by alpadedhia1** [ninjaprox/NVActivityIndicatorView#205]
Hello, 

I added an indicator in storyboard view controller with the settings below. But i cannot see it when i run the app. 

Module is NVActivityIndicatorView.

Please let me know if I am doing something wrong here. 

<img width="254" alt="screen shot 2018-03-15 at 4 54 57 pm" src="https://user-images.githubusercontent.com/36187063/37460670-ec29165a-2871-11e8-9b4c-db462c966e98.png">

Thanks

**Comment by ninjaprox** [comment]
@alpadedhia1: Have you started the animation? As it's not started and hidden by default.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
