### ISSUE TITLE
startAnimating doesn't work in viewDidLoad

### ISSUE THREAD

**Issue by gityubj** [ninjaprox/NVActivityIndicatorView#207]
Hello, 
 I am using this indicator with Rx. However, if you call self.startAnimating in viewDidload, the animation will not work.
It uses the NVActivityIndicatorViewable protocol. Have you resolved any related issues?

**Comment by gityubj** [comment]
When I printed the log, NVActivityIndicatorView seems to be invisible under ViewController. Please fix this bug.

**Comment by ninjaprox** [comment]
@gityubj: Could you share the log? And more context in `viewDidLoad` will also help.

**Comment by Vkt0r** [comment]
@gityubj I recommend you extend RxSwift to support the normal `rx.isAnimating` like the default one that comes with `RxCocoa` and it should work fine.

```swift
extension Reactive where Base: NVActivityIndicatorView {
    
    /// Bindable sink for `startAnimating()`, `stopAnimating()` methods.
    public var isAnimating: Binder<Bool> {
        return Binder(self.base) { activityIndicator, active in
            if active {
                activityIndicator.startAnimating()
            } else {
                activityIndicator.stopAnimating()
            }
        }
    }
}
```

**Comment by ghost** [comment]
You can't use that extension with NVActivityIndicatorViewable protocol right?
