### ISSUE TITLE
Use of unresolved identifier 'NVActivityIndicatorAnimationCircleStrokeSpin'

### ISSUE THREAD

**Issue by Zedd0202** [ninjaprox/NVActivityIndicatorView#208]
Reference #189
I am using Xcode 9.3.  I'm using NVActivityIndicatorView with Cocoapod, version 4.1.1.
but "**Use of unresolved identifier ‘NVActivityIndicatorAnimationCircleStrokeSpin**'" getting errors.
Any solution?

**Comment by ninjaprox** [comment]
@Zedd0202: I tried setting up a new project with CocoaPods `1.4.0` and NVActivityIndicatorView `4.1.1`, and it worked just fine. Please try again with fresh `pod install`. You might also want to refer to  #201 #186 #185.
