### ISSUE TITLE
Main Thread Crash

### ISSUE THREAD

**Issue by ghost** [ninjaprox/NVActivityIndicatorView#209]
When i use `self.stopAnimating()`, i got "This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes." crash. And xcode shows 3 main thread issue on NVActivityIndicatorPresenter.swift line 258, 260 and 262. Is anyone got this crash?

**Comment by ninjaprox** [comment]
@berkerbilgi: Are you calling `stopAnimating()` on the main thread?

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
