### ISSUE TITLE
It seems hard to name a animation name..

### ISSUE THREAD

**Issue by dabing1022** [ninjaprox/NVActivityIndicatorView#21]
Sometimes, It seems hard to name a proper animation name. For example, name a animation class name.

What do you think? 

Cheers!

**Comment by ninjaprox** [comment]
Agree that.
But I think that is not big deal, just think up a name as self-described as possible. Having some meaningful name is at least better than names like `Animation1`, `Animation2`, right?

**Comment by dabing1022** [comment]
Can't agree more. :)
