### ISSUE TITLE
13 Errors found

### ISSUE THREAD

**Issue by EminEmini** [ninjaprox/NVActivityIndicatorView#210]
I uploaded manually `NVActivityIndicatorView` into my project, and it found 13 Errors.
Please check it.

**Comment by ninjaprox** [comment]
@EminEmini: Could you give more detail? Which version `NVActivityIndicatorView` are you using? Xcode version? Swift version? What errors? Log files or screenshots should be fine.

**Comment by EminEmini** [comment]
@ninjaprox I'm using the last version of `NVActivityIndicatorView`, `Swift` and `Xcode`. I deletet files from my project because I had to work more on it, and errors didn't let me to run my project. So I can not provide any screenshot anymore.

**Comment by biajoeknee** [comment]
Same for me. The issue was a missing `import UIKit` in NVActivityIndicatorAnimationCircleStrokeSpin.swift.

**Comment by ninjaprox** [comment]
@btech: I tried on my side, got no error though. Could you try again with a fresh `pod install`? And more details would help investigation.

**Comment by biajoeknee** [comment]
I installed it manually

**Comment by ninjaprox** [comment]
@btech: I guess it's the issue with SwiftLint. If you don't have SwiftLint installed, installing it would solve the issue, or update it to version ~> 0.52.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
