### ISSUE TITLE
Loader doesn't dismiss when there are several windows.

### ISSUE THREAD

**Issue by ievgenleichenko** [ninjaprox/NVActivityIndicatorView#211]
When, for example, alert controller is displayed in new window right after calling stopAnimating, loader doesn't dismiss, because at the time it tries to do so, keyWindow changed.
Our suggestions are:
- cycle through all windows and find loader to dismiss
- store weak reference to the window, displaying the loader

**Comment by ninjaprox** [comment]
#230 addresses this issue by checking all windows on dismiss.
