### ISSUE TITLE
4.2.0 compile issue

### ISSUE THREAD

**Issue by qgliu** [ninjaprox/NVActivityIndicatorView#212]
I use Carthage. In upgrading 4.1.1 to 4.2.0, it failed in compiling. Go back to 4.1.1 works.
Below is the log. Seems some issue in NVActivityIndicatorPresenter with Swift.Int64 to Swift.String.

Loading configuration from '.swiftlint.yml'
Configuration contains invalid keys:
["identifier_name"]
Linting Swift files in current working directory
Linting 'NVActivityIndicatorAnimationDelegate.swift' (1/38)
Linting 'NVActivityIndicatorPresenter.swift' (2/38)
Could not cast value of type 'Swift.Int64' (0x103d6ef80) to 'Swift.String' (0x103d754d8).
/Users/XXX/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/NVActivityIndicatorView/4.2.0/Build/Intermediates.noindex/ArchiveIntermediates/NVActivityIndicatorView/IntermediateBuildFilesPath/NVActivityIndicatorView.build/Release-iphoneos/NVActivityIndicatorView.build/Script-A3BEA4B12075175400F1AF75.sh: line 6:  5158 Abort trap: 6           swiftlint
Command /bin/sh failed with exit code 134

**Comment by ninjaprox** [comment]
@qgliu: Could you try again with a fresh `carthage update`? I tried on my side, but got such error so can't give any suggestion for now.

**Comment by qgliu** [comment]
@ninjaprox Hi, thanks for the quick response. I tried 4.2.0 as well as 4.2.1, same issue at the same place... saying could not cast Swift.Int64 to Swift.String. Moving to 4.1.1 works fine.

I tried the following commands
carthage update  NVActivityIndicatorView --platform iOS --no-use-binaries
or 
carthage update  NVActivityIndicatorView --platform iOS

**Comment by ninjaprox** [comment]
@qgliu: I'm suspecting it has something to do with SwiftLint. Do you have SwiftLint installed on your side? If yes, what version, otherwise try installing it. I'm using `0.25.0`.

**Comment by qgliu** [comment]
@ninjaprox Turns out my SwiftLint is a little outdated. I updated it and it compiled. Thanks!
