### ISSUE TITLE
4.2.0 stopAnimating() not working

### ISSUE THREAD

**Issue by MaikoHermans** [ninjaprox/NVActivityIndicatorView#213]
It seems that the `stopAnimating()` function that becomes available from conforming the `UIViewController` to `NVActivityIndicatorViewable` isn't actually working.

I installed the newest version and tried stopping an animation in multiple ways and it didn't work. Downgraded to 4.1.1 and it worked perfectly fine.

for instance doing (this is just to give an example)

```
override func viewDidLoad() {
super.viewDidLoad()

startAnimating()
stopAnimating()
}
```

would show the ui blocker when running this particular view when version 4.2.0 was installed but it didn't show the ui blocker when 4.1.1 was installed

**Comment by ninjaprox** [comment]
@MaikoHermans: Thanks for reporting! Fixed in `4.2.1`, please help check it out. 🚀
