### ISSUE TITLE
startAnimating() isn't working initially

### ISSUE THREAD

**Issue by ANKITASRI04** [ninjaprox/NVActivityIndicatorView#214]
Hi,
 I am using a table view and hitting an api in view did load .Initially when I try to show NVIndicator view it is not showing anything but if I refresh table view then it is working in another api.The code I am using is:
 NVActivityIndicatorPresenter.sharedInstance.startAnimating(ActivityData())
How to show the loader in viewDidLoad?

**Comment by tudorpopa39** [comment]
I have the same issue. Cannot make it to show the loader on viewDidLoad. I solved it by placing the code in viewDidAppear. But I also search for a better solution

**Comment by ninjaprox** [comment]
@ANKITASRI04, @tudorpopa39: Could you give some snippets? The example project doesn't have this issue.

**Comment by tudorpopa39** [comment]
I created an protocol like this:

```swift
    public protocol LoadingSpinner : NVActivityIndicatorViewable {}

    public extension LoadingSpinner where Self: UIViewController{
    
    public func startLoadingAnimation
        (message : String? = nil,
         type: NVActivityIndicatorType? = nil,
         color : UIColor? = nil,
         backgroundColor : UIColor? = nil){
        
        DispatchQueue.main.async(execute: {
            let size = CGSize(width: 50, height: 50)
            let message = message != nil ? message : ""
            let color = color ?? Constants.Color.galleryGray
            let type = type ?? Constants.DEFAULT_LOADING_SPINNER_TYPE
            let backgroundColor = backgroundColor ?? nil
            self.startAnimating(size, message: message, type: type,
                                color: color, padding: nil, backgroundColor: backgroundColor)
            
            if UIApplication.shared.isIgnoringInteractionEvents {
                UIApplication.shared.endIgnoringInteractionEvents()
            }
            UIApplication.shared.beginIgnoringInteractionEvents()
        });
    }
    
    public func stopLoadingAnimation(){
        DispatchQueue.main.async(execute :{
            UIApplication.shared.endIgnoringInteractionEvents()
            self.stopAnimating()
        });
    }
    }
```
and I extended to the main view controller, and call the _startLoadingAnimation_ in the _viewDidAppear_
```swift
    class ViewController: UIViewController, LoadingSpinner  {

         override func viewDidLoad() {
              super.viewDidLoad()
         }

         override func viewDidAppear(_ animated: Bool) {
               super.viewDidAppear(animated)
               self.startLoadingAnimation(backgroundColor: .clear)
         }
    }
```

**If i place the _startLoadingAnimation_ in the _viewDidLoad_ method, it simply doesn't do anything.**

**Comment by ninjaprox** [comment]
@tudorpopa39: I tried the same setup (new, clean project) as you provided, it works in `viewDidLoad` though. Not sure if I missed out anything, or what causes the issue on your side.

**Comment by peterxiaoyun** [comment]
I got the same issue. In my case, if I put show/hide logic in super viewController, it won't show the view., but if I put the logic in child viewController, it shows

I checked the view hierarchy, looks like if I put in super viewController and call startAnimating, the indicator is shown behind the child main view, and if put logic in child viewController, then show in front of the main view

**Comment by tudorpopa39** [comment]
it looks that after updating to version 4.3.0, the spinner startAnimating even if I put it in the **viewDidLoad**. I don't know if this version fix the issue or another, but now it works. 
Thank you. Cheers

**Comment by ninjaprox** [comment]
@peterxiaoyun: In your case, it likely happens if you present the child VC after the UI blocker has displayed.
@tudorpopa39: Thanks, good to know that.

**Comment by peterxiaoyun** [comment]
Maybe I didn't say clearly. My case is I put the show/hide functions in my super VC, and the show and hide is trigged by my view model subject. So, basically the animating show and hide is automatically trigged based on if the view model subject receives data or not. If I put the subscription of the subject code in viewDidLoad, the animating view will show behind the VC'c main view. However, If I put some delay for the subscription, it will show in front of the main view which is visible then. Btw, my version is 4.3.0

**Comment by dashvlas** [comment]
@peterxiaoyun @ninjaprox  same issue :(

**Comment by aabantariqmurtaza** [comment]
@dashvlas  you got its solution?

**Comment by dashvlas** [comment]
@aabantariqmurtaza I've just changed the library to another one

**Comment by aabantariqmurtaza** [comment]
@dashvlas  what's your email id. i need to talk

**Comment by dashvlas** [comment]
@aabantariqmurtaza dariakorneichuk@icloud.com

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
