### ISSUE TITLE
tvOS target support

### ISSUE THREAD

**Issue by gabors** [ninjaprox/NVActivityIndicatorView#221]
Thanks for building this great library!
Would you be able to add support for a tvOS framework target please?

**Comment by ghost** [comment]
There is a tvOS branch you can try, it is a bit outdated. I'll try to update that branch with the latest master when I get a chance.

**Comment by gabors** [comment]
Thank you, any progress on this?

**Comment by gabors** [comment]
Hi @ninjaprox 
We love your framework, any chance you can add a tvOS target please?
Merry Christmas !

**Comment by ninjaprox** [comment]
@gabors: Check out `4.5.0`, the tvOS target has been added.
