### ISSUE TITLE
How to change "circleStrokeSpin" animation to have a larger line?

### ISSUE THREAD

**Issue by paulocoutinhox** [ninjaprox/NVActivityIndicatorView#222]
Hi,

How to change "circleStrokeSpin" animation to have a larger line?

I want make something like Android loader. See:

![image](https://user-images.githubusercontent.com/395096/42998471-96326390-8bf0-11e8-8479-927b278a1ace.png)

Thanks.

**Comment by ninjaprox** [comment]
@prsolucoes: All animations are prebuilt with specific specs, and cannot be customized (except size and color). In case it's needed, you can fork this repo and modify the animation according to your need.
