### ISSUE TITLE
FadeOutAnimation

### ISSUE THREAD

**Issue by Dohab** [ninjaprox/NVActivityIndicatorView#226]
`self.stopAnimating(FadeOutAnimation)` cause error
`Cannot convert value of type '(FadeOutAnimation).Type' (aka '((UIView, @escaping () -> ()) -> ()).Type') to expected argument type 'FadeOutAnimation?' (aka 'Optional<(UIView, @escaping () -> ()) -> ()>')`

Swift 4

**Comment by ninjaprox** [comment]
@Dohab: How do you use or implement a specific `FadeOutAnimation`?

**Comment by vamshikpadala** [comment]
NVActivityIndicatorPresenter.sharedInstance.startAnimating(activityData, <#FadeInAnimation?#>)

Could you please help me in how to use FadeInAnimation and FadeOutAnimation?

**Comment by ninjaprox** [comment]
@vamshikpadala: You can check out [DEFAULT_FADE_IN_ANIMATION](https://github.com/ninjaprox/NVActivityIndicatorView/blob/4939dacbe3f0febbbd72782b55c3b0fb891fec3a/Source/NVActivityIndicatorView/NVActivityIndicatorView.swift#L394) for the example of how to implement a `FadeInAnimation`, and similar for `FadeOutAnimation`. Then call `startAnimation` or `stopAnimation` with a `FadeInAnimation` or `FadeOutAnimation` respectively ([doc here](https://github.com/ninjaprox/NVActivityIndicatorView#fade-inout-animation)).

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
