### ISSUE TITLE
Unable to import NVActivityIndicatorView in Class

### ISSUE THREAD

**Issue by bharatbyan** [ninjaprox/NVActivityIndicatorView#228]
After installing via cocoa-pods, I'm having the issue, unable to import the NVActivityIndicatorView.

![screen shot 2018-08-19 at 4 23 49 pm](https://user-images.githubusercontent.com/3232787/44308114-ccd58000-a3cc-11e8-8f10-e21c3bf91ad9.png)

**Comment by ninjaprox** [comment]
@111jaam: Could you try again with a clean setup of CocoaPods? This issue is likely due to CocoaPods setup.

**Comment by ninjaprox** [comment]
It seems to duplicate #235.
