### ISSUE TITLE
When will there be a release or a separate branch for Swift 4.2?

### ISSUE THREAD

**Issue by alexanderkhitev** [ninjaprox/NVActivityIndicatorView#231]
Hello @ninjaprox! When will there be a release or a separate branch for Swift 4.2?

**Comment by ninjaprox** [comment]
@alexanderkhitev: There'll be a new version as soon as Xcode 10 releases officially. Stay stunned 😉

**Comment by MSavisko** [comment]
@alexanderkhitev
Workaround:
`pod 'NVActivityIndicatorView', :git => 'https://github.com/ninjaprox/NVActivityIndicatorView.git', :branch => 'swift4.2'`

**Comment by alexanderkhitev** [comment]
@MSavisko 
Thanks, I made it. I asked this question when there was no Swift 4.2 branch

**Comment by muhasturk** [comment]
just for information Xcode 10 final version has been released.

**Comment by ninjaprox** [comment]
@alexanderkhitev: Version 4.4.0 with Swift 4.2 is out. 🚀

**Comment by alexanderkhitev** [comment]
@ninjaprox thank you!
