### ISSUE TITLE
In Xcode version 10, no such file or directory: ‘NVActivityIndicatorView’ error

### ISSUE THREAD

**Issue by SyedSaal** [ninjaprox/NVActivityIndicatorView#235]
Hi, I'm unable to run my application due to following error occurred

no such file or directory: ‘NVActivityIndicatorView’

in Xcode version 10 .

Could you please let me know , how to fix it or update the existing NVActivityIndicatorView

**Comment by ninjaprox** [comment]
@SyedSaal: Could you try again with a clean `pod install`?

**Comment by lmcmz** [comment]
@ninjaprox   I tried all the commands below to clean up pod. 

1. `rm -rf ~/Library/Caches/CocoaPods`
2. `rm -rf Pods` 
3. `rm -rf ~/Library/Developer/Xcode/DerivedData/*` 
4. `pod deintegrate` 
5. `pod setup` 
6. `pod install`

I still cannot import NVActivityIndicatorView in Xcode 10. :(

**Comment by SyedSaal** [comment]
Hi, I fixed the issue:

In **Xcode** _menu_, Goto **File** and select **workspace settings** and there `change` the Build System to **Legacy Build System** from **Default**.
