### ISSUE TITLE
Outdated version compile errors

### ISSUE THREAD

**Issue by SooqaEffect** [ninjaprox/NVActivityIndicatorView#236]
How to fix this?
<img width="311" alt="pods xcodeproj 2018-09-24 22-39-38" src="https://user-images.githubusercontent.com/37033207/45974696-cc26ae00-c04a-11e8-8ccc-2fafe46ef622.png">

**Comment by ninjaprox** [comment]
@SooqaEffect: What version of the pod are you using?

**Comment by promehul** [comment]
Any updates about resolving this issue?

**Comment by parnaudd** [comment]
@ninjaprox Same error for me using version from cocoapods (4.3.0 but i am not sure)

EDIT :  problem solved using command

```
$ pod install --repo-update
````

And version 4.4.0 has been installed
```
 "Installing NVActivityIndicatorView 4.4.0 (was 4.3.0 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
```
