### ISSUE TITLE
How To Add Text ?

### ISSUE THREAD

**Issue by moheny** [ninjaprox/NVActivityIndicatorView#24]
First Of All , let me start by saying it's a great project ! 
I've tried to edit it and add Text to the Indicator, but without success. 
Is it possible ?

**Comment by ninjaprox** [comment]
Thank you!
At the moment, it doesn't support text in indicator. Maybe it is coming in the next update. However, your pull request is always welcome.

**Comment by winkelsdorf** [comment]
@moheny I won't say add text directly to this library, if it's not going to be animated.

Text can be too different, think about it's position, or attributedText, different font handling for dynamicType and UIAccessibility contrasts (i.e. dark colors, increased contrast, white point). The latter should receive NSNotifications for screen updates etc. This might get a little complex.

Depending on what you want to do, you can simply add a Label to your Storyboard (or in code) and use AutoLayout to position both together.

Displaying text and activity animation are separate things that should be likely kept separated. Labels, Buttons are available as part of UIKit and you can use them as usual.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
