### ISSUE TITLE
Swift 4.2 updates

### ISSUE THREAD

**Issue by BailyTroyer** [ninjaprox/NVActivityIndicatorView#244]
Upon installing the Podfile, my project has been littered with 24 issues mostly with renaming changes with the most current version of swift, many of which have been "obsoleted in swift3" based on Xcode.

**Comment by promehul** [comment]
Any updates regarding this?

**Comment by ninjaprox** [comment]
Version `4.4.0` has been upgraded to use Swift `4.2`. Please check and try again with clean `pod install` if you're not using the latest version.

**Comment by ninjaprox** [comment]
Might be solved in `4.4.1`.

**Comment by ankitthakur** [comment]
In XCode 10.1, we are getting swift conversion warning for NVActivityIndicatorView (4.4.1). Need to reopen this issue.

**Comment by ninjaprox** [comment]
@ankitthakur: Could you check out `4.5.0`, and see if the issue still occurs? `swift_version` in the Podspec file has been changed to `4.2` instead of `4.0`.

**Comment by KrisanuWeavers** [comment]
showing error Command PhaseScriptExecution failed with a nonzero exit code. How to overcome from it . Help me

**Comment by arindam94** [comment]
showing error Command PhaseScriptExecution failed with a nonzero exit code. How can i solve this issue. My project is on swift 4.2 and ios 11.3

**Comment by ninjaprox** [comment]
@KrisanuWeavers, @arindam94: Where did you get the error from? If possible, please paste the context lead to the error as well as the full error here.

**Comment by arindam94** [comment]
after installing the pod. This is the only pod I have in my project.  I attached the screenshot of error . please go through it [and]([url](url)) let me know. Its very urgent for `me`
![screenshot 2019-01-11 at 12 24 15 pm](https://user-images.githubusercontent.com/30508758/51018073-4ba9a000-159c-11e9-9da1-0a87e067ec6a.png)

``

**Comment by arindam94** [comment]
@ninjaprox  please help me

**Comment by ninjaprox** [comment]
@arindam94: Have you tried a clean `pod install`? If the issue still occurs, please use `4.4.x` instead at the moment. I'll be having a look on this.

**Comment by ninjaprox** [comment]
Close as it's likely a CocoaPods integration issue rather than the library itself. Please create a new issue with full detail if you encounter it.
