### ISSUE TITLE
Type 'CAMediaTimingCuntionName' aka 'NSString' has no member 'linear'

### ISSUE THREAD

**Issue by Michele404** [ninjaprox/NVActivityIndicatorView#246]
I got this error
Type 'CAMediaTimingCuntionName' aka 'NSString' has no member 'linear'

I got last pod

**Comment by husky-tech** [comment]
I have same issues.

**Comment by ninjaprox** [comment]
Could you give more detail like Xcode version, Swift version, etc.?

**Comment by Michele404** [comment]
Swift version 4.2
xCode last

**Comment by ninjaprox** [comment]
Could you try again with a fresh `pod install` in the existing project or a new fresh project? Pasting `Podfile.lock` here might also help.

**Comment by x-hovo-x** [comment]
Similar issue: 25 Compile Error
First one
animation.timingFunction = CAMediaTimingFunction(name: kCAMediaTimingFunctionLinear) ('kCAMediaTimingFunctionLinear' has been renamed to 'CAMediaTiming)

xcode: 10.1
swift: 4.2

Podfile.lock ----------- START -------------
PODS:
  - NVActivityIndicatorView (4.3.0):
    - NVActivityIndicatorView/Presenter (= 4.3.0)
  - NVActivityIndicatorView/Presenter (4.3.0)

DEPENDENCIES:
  - NVActivityIndicatorView

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - NVActivityIndicatorView

SPEC CHECKSUMS:
  NVActivityIndicatorView: 963f62bf9f993fcf23218e55958e5b1761b9504c

PODFILE CHECKSUM: 3ae5044e9fc391a1824621f90e62e2920fff9ea2

COCOAPODS: 1.5.2
Podfile.lock ----------- END -------------

P.S.
The project is completely new, simple view controller

**Comment by ninjaprox** [comment]
Please try again with at least version [`4.4.0`](https://github.com/ninjaprox/NVActivityIndicatorView/releases/tag/4.4.0) which migrated to Swift 4.2. You might need to run `pod repo update && pod install` or `pod install --repo-update` to update the CocoaPods repo so that you're guaranteed to get the latest version of the pod.

**Comment by x-hovo-x** [comment]
Sorry haven't seen version is not 4.3.0, works 
Thank YOU!
