### ISSUE TITLE
Update message within process

### ISSUE THREAD

**Issue by garanda21** [ninjaprox/NVActivityIndicatorView#247]
There's any way to update the message inside async block, eg:

Processed 1/1000
Processed 115/1000
Processed 500/1000

etc...

Thanks in advance.

**Comment by ninjaprox** [comment]
You can use `setMessage(_: String?)`. There is an example for this in the example project.

**Comment by garanda21** [comment]
I wasn't use this  NVActivityIndicatorPresenter.sharedInstance mode, now I've changed everything and it works with `setMessage(_: String?)`, thanks for your help.
