### ISSUE TITLE
Unable to build project with Carthage 

### ISSUE THREAD

**Issue by miharancic** [ninjaprox/NVActivityIndicatorView#251]
After Carthage update / bootstrap version 4.5.0 is downloaded and built, Carthage doesn't report any problems. But during project build I get an error "No such module NVActivityIndicatorView". I am using `import NVActivityIndicatorView` from the beginning. After Carthage update, Xcode completion suggests I should import "NVActivityIndicatorView_iOS" but still can't build with the same error message ("No such module NVActivityIndicatorView_iOS").

I have been using NVActivityIndicatorView for over a year with no problems... until now.

Could you please investigate?

Thanks

**Comment by BruceBC** [comment]
Having the same issue.

**Comment by joshuapoq** [comment]
Found the same issue - we just need to change the product module name of the `-iOS` target.

**Comment by ninjaprox** [comment]
Sorry for the issue, this is probably due to the recent change of the target name in version `4.5.0`. `4.5.1` has been out to address this issue with one caveat of changing to `import NVActivityIndicatorView_iOS` ([README updated](https://github.com/ninjaprox/NVActivityIndicatorView#usage)).

Please help verify the fix.

**Comment by miharancic** [comment]
Fix verified, everything working as expected. Thank you and keep up the good work :)

**Comment by ninjaprox** [comment]
The ongoing discussion regarding the matter is on #259. Please expect the change in the upcoming release, which will revert back to `import NVActivityIndicatorView`. Sorry for this inconvenience.

**Comment by ninjaprox** [comment]
Now with `4.6.0`, you can simply `import NVActivityIndicatorView` as before.
