### ISSUE TITLE
Which version to use for Xcode 9.4.1?

### ISSUE THREAD

**Issue by hrtlkr29** [ninjaprox/NVActivityIndicatorView#255]
For some reasons, I have to use Xcode version 9.4.1. After your newest update of NVActivityIndicatorView, i can't continue using the library anymore because it requires Xcode 10.1
Is there any way to install older versions of this library, for instance, version 4.0.0? I tried 
`pod 'NVActivityIndicatorView' '~> 4.0.0'
`
But it didn't work.
Thank you very much!

**Comment by ninjaprox** [comment]
`~> 4.0.0` will resolve to `4.5.1`, which requires Xcode 10.1 and Swift 4.2, according to [this](https://guides.cocoapods.org/syntax/podfile.html#pod). Therefore, `~> 4.3.0` might work.

**Comment by hrtlkr29** [comment]
~> 4.3.0 is working perfectly with Xcode 9.4.1. Thank you very much for your fast reply!
