### ISSUE TITLE
Error since NVActivityIndicatorAnimationBallDoubleBounce

### ISSUE THREAD

**Issue by KoCMoHaBTa** [ninjaprox/NVActivityIndicatorView#257]
I've just downloaded the latest version and i'm getting compile error from `NVActivityIndicatorView.swift` line 316 - **Use of unresolved identifier 'NVActivityIndicatorAnimationBallDoubleBounce'**

**Comment by ninjaprox** [comment]
Thanks for the issue. This is origin from #253, but haven't released in a new version. If you're using `master` branch, I'd suggest specifying a version instead to avoid breaks during development.

**Comment by KoCMoHaBTa** [comment]
Thanks
