### ISSUE TITLE
Please update de function kCAMediaTimingFunctionEaseInEaseOut of commit df833bf

### ISSUE THREAD

**Issue by MatCruz** [ninjaprox/NVActivityIndicatorView#261]
Please, update a line 48 because the function kCAMediaTimingFunctionEasyInEaseOut is wrong, the correct function is kCAMediaTimingFunctionEaseInEaseOut of file Source/NVActivityIndicatorView/Animations/NVActivityIndicatorAnimationBallDoubleBounce.swift changed on commit "df833bf"

**Comment by ninjaprox** [comment]
Thanks for the issue. It has been fixed and release in `4.6.1`.
