### ISSUE TITLE
Xcode 10 and swift 4.2 error

### ISSUE THREAD

**Issue by albertml** [ninjaprox/NVActivityIndicatorView#263]
Command CompileSwift failed with a nonzero exit code using version 4.6.1

**Comment by ninjaprox** [comment]
Please give more details, e.g. Xcode version, using CocoaPods or Carthage, Swift version. A copy of full error message also helps.

**Comment by AhmadDurrani579** [comment]
Xcode 10.1 
swift 4.2 
 pod 'NVActivityIndicatorView'

Issue
 'NVActivityIndicatorType' cannot be constructed because it has no accessible initializers
NVActivityIndicatorType not getting this value in swift 4.2
        startAnimating(size, message: "", messageFont: nil , type: NVActivityIndicatorType(rawValue: 6), color:UIColor.white   , padding: nil, displayTimeThreshold: nil, minimumDisplayTime: nil, backgroundColor: nil , textColor: UIColor.white)

**Comment by ninjaprox** [comment]
@albertml: Please use `enum` value (e.g. `.ballPulse`) instead of constructing from a raw value as `NVActivityIndicatorType` now doesn't conform `Int` any more.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
