### ISSUE TITLE
Error when using carthage

### ISSUE THREAD

**Issue by acecilia** [ninjaprox/NVActivityIndicatorView#265]
After installing the last version 4.6.1 with carthage and adding the `NVActivityIndicatorView` and `NVActivityIndicatorViewAppExtension` to the project, I get the following error when running on the simulator:

`Found bundle at /Users/user/Library/Developer/XCTestDevices/EDE1D09E-7C8A-4A03-B122-55BA26CA34CA/data/Library/Caches/com.apple.mobile.installd.staging/temp.7eRVwf/extracted/Payload/AppName.app/Frameworks/NVActivityIndicatorViewAppExtension.framework with the same identifier (me.vinhis.NVActivityIndicatorView) as bundle at /Users/user/Library/Developer/XCTestDevices/EDE1D09E-7C8A-4A03-B122-55BA26CA34CA/data/Library/Caches/com.apple.mobile.installd.staging/temp.7eRVwf/extracted/Payload/AppName.app/Frameworks/NVActivityIndicatorView.framework`

**Comment by ninjaprox** [comment]
Could you try again with a clean `carthage build`? There's a recent change on the product name which probably messed up `carthage build`. #251 might be relevant.

**Comment by acecilia** [comment]
I just removed `NVActivityIndicatorView` and `NVActivityIndicatorViewAppExtension` from my `Build/iOS` folder. Having `github "ninjaprox/NVActivityIndicatorView" == 4.6.1` in my cartfile I run `carthage update --platform ios`. The build of the app finish successfully (so it is not a build error), the error shows up when installing it to simulator, and the full Xcode error says:

- Title: `This app could not be installed at this time.`
- Body: `Found bundle at /Users/user/Library/Developer/XCTestDevices/EDE1D09E-7C8A-4A03-B122-55BA26CA34CA/data/Library/Caches/com.apple.mobile.installd.staging/temp.7eRVwf/extracted/Payload/AppName.app/Frameworks/NVActivityIndicatorViewAppExtension.framework with the same identifier (me.vinhis.NVActivityIndicatorView) as bundle at /Users/user/Library/Developer/XCTestDevices/EDE1D09E-7C8A-4A03-B122-55BA26CA34CA/data/Library/Caches/com.apple.mobile.installd.staging/temp.7eRVwf/extracted/Payload/AppName.app/Frameworks/NVActivityIndicatorView.framework`

**Comment by ninjaprox** [comment]
Oh I got it. You should either use `NVActivityIndicatorView` or `NVActivityIndicatorViewAppExtension`. In fact, `NVActivityIndicatorView` is inclusive of `NVActivityIndicatorViewAppExtension`. You only need to use `NVActivityIndicatorViewAppExtension` in an app extension.

**Comment by acecilia** [comment]
Okey, got it, thanks!
