### ISSUE TITLE
You removed support for init via raw value

### ISSUE THREAD

**Issue by ES5017** [ninjaprox/NVActivityIndicatorView#266]
How am I meant to initialize from a number raw value now?

**Comment by ES5017** [comment]
nvm, simply can get the index:

nvLoadingIconTypeIndex = NVActivityIndicatorType.allCases.index(of: NVActivityIndicatorHelper.Constants.type)!

and init from that index:

	NVActivityIndicatorHelper.Constants.type = NVActivityIndicatorType.allCases[nvLoadingIconTypeIndex]

**Comment by ninjaprox** [comment]
Any reasons you have to use a raw number instead of a enum case?

**Comment by ES5017** [comment]
Yes, I so i can change the loading icon remotely using firebase remote config (without updating the app), and that only allows very primitive types like strings and numbers etc.

**Comment by ninjaprox** [comment]
Interesting! I think we can close this issue as you already have the solution for it.
