### ISSUE TITLE
How To Add footer list ?

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [ninjaprox/NVActivityIndicatorView#27]
I appreciated your project.I want to  add footer list. my problem is that this view cover all the page width and It do not accept the size that I put for it.

**Comment by ninjaprox** [comment]
@AlirezaGhanbarinia: Could you give more details?

**Comment by AlirezaGhanbarinia** [comment]
I have used indicator = BallPulseSync for loading in list view footer(in list pagination).
the problem is that the balls fill the list's width.
my question is how to set size for balls?

**Comment by ninjaprox** [comment]
Have you tried `activityIndicatorView.size`? You cannot set size of balls, they are calculated base on `activityIndicatorView.size` instead.
Note that up to `v2.3`, `activityIndicatorView.frame.size` is different with `activityIndicatorView.size`. Therefore, in your case, I think `activityIndicatorView.frame.size.width` = list's width and `activityIndicatorView.size.width` < list's width.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
