### ISSUE TITLE
How to show indicator in UIWindow

### ISSUE THREAD

**Issue by VivekVithlani** [ninjaprox/NVActivityIndicatorView#275]
Hello,

I try to load NVActivityIndicatorView in UIWindow.
I have created Singleton class and get reference of UIWindow then show indicator method in Singleton class.
However I call / show /display indicator in UIWindow from Singleton class.

**Comment by CearsKhush** [comment]
Did you got the solution?

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
