### ISSUE TITLE
s.swift_version          = '5.0'

### ISSUE THREAD

**Issue by crspybits** [ninjaprox/NVActivityIndicatorView#277]
Is there a reason to have:
    `s.swift_version          = '5.0'`
and not 
    `s.swift_version          = '4.2'`
in the .podspec?

It seems the library still builds fine with Swift 4.2 and this gives more backwards compatibility too (e.g., to Xcode 10.1).

Thanks for your consideration,
Chris.

**Comment by ninjaprox** [comment]
@crspybits: As the latest version `4.7.0` has been migrated to Swift 5.0, it makes sense to update the `Podspec` file appropriately. If by any constraints, you still have to use Swift 4.2, I'd suggest using versions lower than `4.7.0`.
