### ISSUE TITLE
Archive Failing with NVActivityIndicatorView and Extension version installed with Cocoa pods

### ISSUE THREAD

**Issue by Gardenhire** [ninjaprox/NVActivityIndicatorView#278]
With the new Xcode 10.2 update I cannot archive an application that has the NVActivityindicatorview and the extension version of the framework, both installed using cocoa pods. I have tried changing the Product and Module name in "Build Settings" for the Extension target so that it is unique, but the only fix that works is changing to the "Legacy Build System". Error message is below:

Multiple commands produce '/Users/.../Library/Developer/Xcode/DerivedData/.../Build/Intermediates.noindex/ArchiveIntermediates/Skadaddle/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/NVActivityIndicatorView.framework':
1) Target 'NVActivityIndicatorView' has create directory command with output '/Users/.../Library/Developer/Xcode/DerivedData/.../Build/Intermediates.noindex/ArchiveIntermediates/.../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/NVActivityIndicatorView.framework'
2) Target 'NVActivityIndicatorView-AppExtension' has create directory command with output '/Users/.../Library/Developer/Xcode/DerivedData/.../Build/Intermediates.noindex/ArchiveIntermediates/.../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/NVActivityIndicatorView.framework'

**Comment by ninjaprox** [comment]
@Gardenhire: What version are you using? Are you using `pod 'NVActivityIndicatorView'` or `pod 'NVActivityIndicatorView/AppExtension'`?

**Comment by Gardenhire** [comment]
I am using version 4.7. I have both installed via my pod file. I use the activity indicator view in my application and in a notification extension.

**Comment by therauli** [comment]
We had the same issue while using Carthage. [I made a PR that fixed the issue for us](https://github.com/ninjaprox/NVActivityIndicatorView/pull/288).

**Comment by huseyinmetin** [comment]
I had the same issue. My problem was that installed with both as cocoapods and in as project.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
