### ISSUE TITLE
NVActivityInidicatorView with gradient 

### ISSUE THREAD

**Issue by KrystynaKruchkovska** [ninjaprox/NVActivityIndicatorView#279]
Hi,

is it possible to set up the NVActivityInidicatorView with gradient color? 

For now initialiser looks like this:

init(frame: CGRect, type: NVActivityIndicatorType? = nil, color: UIColor? = nil, padding: CGFloat? = nil)

but maybe there's some trick that could be done to achieve gradient color instead of one color.

If it's not possible, it could be feature added at some point.

**Comment by ninjaprox** [comment]
@KrystynaKruchkovska: Sounds like a nice add-on to have. It seems not too difficult to implement this. Feel free to create a PR if you have some time.

**Comment by piv199** [comment]
@ninjaprox This feature seems to be really cool. And I'd like to contribute to this project implementing this feature.

1) I'd like to create a protocol `NVActivityIndicatorColorProvider` which will be responsible for creating UIColor. This will allow custom implementations for specific needs. Basically we need to pass `size` that  color will be applied to. Will it make sense to pass type of the activity indicator or even an instance of `NVActivityIndicatorView` - this could make sense if we treat it as color delegate?
2) I found that some views could be colored in different ways... For example we have view of type `audioEqualizer` and we could apply for example pattern for each line separately or we could have a pattern for the whole view. So basically when we have multiple objects in a view we could style them whatever we like. What I would like to propose is to have multiple delegates for different types (for example delegate `NVActivityIndicatorLinesColorDelegate` could be applied to 14, 15, 19, 20, 31 in common). What do you think of this? Maybe someone has clearer vision of it?

I'm also wondering what `color` property should return if we applied custom delegate and styled objects separately? Make assertion so there isn't any custom color applier, return some default value and log a warning?

On the other side, as a user it would be cool if I he could just pass some (UIColor, CGFloat) and it will style indicator by default. What is the default for each view type?

This seems to be interesting and not that easy task if we would like to make great customization experience) 

@ninjaprox I'm looking forward to your response just to get your thoughts of how this could fit this library. Feel free to reply in any case.

**Comment by ninjaprox** [comment]
@piv199: Thanks for your interest. I have my thought [here](https://github.com/ninjaprox/NVActivityIndicatorView/issues/267#issuecomment-467465790) regarding customization. That being said, I totally support the idea of having gradients for animations, even the background. Sure we can either have a uniform color for animation or different colors for different components in the animation. The former seems to be a good start. With color, we might do the same way as animation. In other words, we have a set of predefined good-looking gradients, plus a custom one—animations don't have this yet. Then we decorate animations with these gradients. What do you think? And you're welcome to contribute to this. 🎉

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
