### ISSUE TITLE
NVActivityIndicatorPresenter start animation method change but no description anywhere to use

### ISSUE THREAD

**Issue by Github-Prashant** [ninjaprox/NVActivityIndicatorView#283]
Hi,

I am bit disappointing about changes like :-
NVActivityIndicatorPresenter.sharedInstance.startAnimating(activityData)
NVActivityIndicatorPresenter.sharedInstance.startAnimating(activityData, <#T##fadeInAnimation: FadeInAnimation?##FadeInAnimation?##(UIView) -> Void#>)

I did not get it for hot to use of that changes. If I don't want to change it then which pod version I need to maintain with Swift 4.2 and Xcode 10.2

**Comment by ninjaprox** [comment]
@Github-Prashant: In `4.7.0`, `fadeInAnimation` param is set to `nil` by default so you still can use the same API without any changes.
