### ISSUE TITLE
Unexpected version number in 'available' attribute for non-specific platform '*' 

### ISSUE THREAD

**Issue by fstigre** [ninjaprox/NVActivityIndicatorView#284]
Hi, I'm using `NVActivityIndicatorView` in `Xcode to 10.2.1` and `Swift 4.2`using `Cocoapods` and I'm getting a few warnings. 

In `public final class NVActivityIndicatorView: UIView` line `435`I'm getting the following warning.
> Unexpected version number in 'available' attribute for non-specific platform '*'

In `public extension NVActivityIndicatorViewable where Self: UIViewController` line `57 and 88` I'm seeing the following warning.

> 'public' modifier is redundant for instance method declared in a public extension

What can I do to fix these warnings?

The fix for the first warning is described here:
https://stackoverflow.com/questions/55721287/warning-unexpected-version-number-in-available-attribute-for-non-specific-pl

They both look like easy fixes but I'm not sure how to handle this since I'm using `Cocoapods` and I'm afraid to break something if I try to manually fix them.

Can someone be so kind and help me resolve these warnings?

By the way, `NVActivityIndicatorView` is a great library, keep up the good work.

Thanks a lot!

**Comment by ninjaprox** [comment]
@fstigre: Hmm seems they have been resolved in #274. Let's try with `4.7.0` first, though it should be for Swift 5.

**Comment by fstigre** [comment]
So, what you're saying is that it was resolved in the latest version (4.7.0 / Swift 5)? Thanks.

**Comment by ninjaprox** [comment]
@fstigre: Let me know if it helps.

**Comment by fstigre** [comment]
Thanks.
