### ISSUE TITLE
I could let it appear and disappear but I want to change size, color, type and message I use this class and 2 methods .

### ISSUE THREAD

**Issue by GergesEid** [ninjaprox/NVActivityIndicatorView#287]
import UIKit
import NVActivityIndicatorView
import Foundation

class Loading: UIViewController, NVActivityIndicatorViewable {

    func startProgress() {
        
        let size = CGSize(width: 30, height: 30)
        let color = UIColor.blue

        let type = NVActivityIndicatorType.ballScale
        let message = "Loading"

        startAnimating(size, message:message, type:type, color:color)
    }

    func stopProgress() {
        self.stopAnimating()
    }

}

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
