### ISSUE TITLE
Is it possible change the speed of animation?

### ISSUE THREAD

**Issue by sunlyear** [ninjaprox/NVActivityIndicatorView#29]
I love the providing features in NVActivityIndicatorView, but I wonder if it is possible to manage the speed of animation? I want it to be slower than this.

**Comment by ninjaprox** [comment]
I think there is one possible way that is changing `layer.speed` (you can check implementation of `startAnimation()`). I also tried setting value less than 1, it makes the animation slower.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.

**Comment by Drusy** [comment]
Setting a layer speed value less than 1 makes the animation stuck, any idea ?
