### ISSUE TITLE
Customizing Animation Speed

### ISSUE THREAD

**Issue by SirWellington** [ninjaprox/NVActivityIndicatorView#293]
This has been requested before (See #29). 

Is there a means for tuning the animation speed? I tried the `layer.speed = 0.5`, but that stopped the animation.

Any ideas?

Thanks,
Wellington

**Comment by ninjaprox** [comment]
@SirWellington: Setting `layer.speed` is actually a hack to slow down animations, and sure it won't work with some. Each animation comes with a set of tailored values, like its characteristics, for the best result. Tuning an animation speed, ideally, means we need a new set of values that fit that speed. It might be interesting to have speed variant, for example `.normal`, `.slow`, `.fast`. Any thoughts?

**Comment by aleksmutlu** [comment]
Yeah it would be nice if we could change the animation speed.

**Comment by ninjaprox** [comment]
My opinion regarding this https://github.com/ninjaprox/NVActivityIndicatorView/issues/267#issuecomment-467465790
