### ISSUE TITLE
[NVActivityIndicatorPresenter] Allow specifying the view in which to show the loading indicator

### ISSUE THREAD

**Issue by jzting** [ninjaprox/NVActivityIndicatorView#294]
Currently the loading indicator is shown over the whole window. It would be nice to be able to specify where to show the indicator, e.g. in a child view controller view.

**Comment by ninjaprox** [comment]
It's possible to do this by using `NVActivityIndicatorView` and add it to any views as your need.

**Comment by jzting** [comment]
Thanks!
