### ISSUE TITLE
Cannot install app

### ISSUE THREAD

**Issue by LinusGeffarth** [ninjaprox/NVActivityIndicatorView#297]
After upgrading to Xcode 11.3, I cannot run my app on the simulator anymore and get the following error:

>This app could not be installed at this time.
Domain: IXUserPresentableErrorDomain
Code: 1
Failure Reason: Could not install at this time.
Recovery Suggestion: Found bundle at /Users/<username>/Library/Developer/CoreSimulator/Devices/5E7081DE-66D1-436A-A6C7-91AB5442888C/data/Library/Caches/com.apple.mobile.installd.staging/temp.JUHLow/extracted/My App.app/Frameworks/NVActivityIndicatorViewAppExtension.framework with the same identifier (me.vinhis.NVActivityIndicatorView) as bundle at /Users/<username>/Library/Developer/CoreSimulator/Devices/5E7081DE-66D1-436A-A6C7-91AB5442888C/data/Library/Caches/com.apple.mobile.installd.staging/temp.JUHLow/extracted/My App.app/Frameworks/NVActivityIndicatorView.framework
--
Found bundle at /Users/<username>/Library/Developer/CoreSimulator/Devices/5E7081DE-66D1-436A-A6C7-91AB5442888C/data/Library/Caches/com.apple.mobile.installd.staging/temp.JUHLow/extracted/My App.app/Frameworks/NVActivityIndicatorViewAppExtension.framework with the same identifier (me.vinhis.NVActivityIndicatorView) as bundle at /Users/<username>/Library/Developer/CoreSimulator/Devices/5E7081DE-66D1-436A-A6C7-91AB5442888C/data/Library/Caches/com.apple.mobile.installd.staging/temp.JUHLow/extracted/My App.app/Frameworks/NVActivityIndicatorView.framework
Domain: MIInstallerErrorDomain
Code: 57
User Info: {
    FunctionName = "-[MIInstallableBundle performPreflightWithError:]";
    LegacyErrorString = DuplicateIdentifier;
    SourceFileLine = 391;
}
--

I have installed the latest release of NVActivityIndicator through Carthage.

**Comment by LinusGeffarth** [comment]
Update: I removed the library from my Cartfile and removed the linked binary, and then installed it though CocoaPods. Now my app is running as usual. Might be worth looking into the Carthage issue anyway.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
