### ISSUE TITLE
Is it possible to set the thickness of circleStrokeSpin

### ISSUE THREAD

**Issue by OudomSec** [ninjaprox/NVActivityIndicatorView#298]
Is it possible to set the thickness of circleStrokeSpin, because I want the thickness of circleStrokeSpin a bit thicker and bigger?

**Comment by jasmit34** [comment]
I want same things, have you done it?

**Comment by OudomSec** [comment]
Sorry for the late reply, since the library can't create the thickness of the circleStrokeSpin, we've created and customized our own loading view instead.

**Comment by ninjaprox** [comment]
Short answer, no at the moment. The reason is similar to my comment [here](https://github.com/ninjaprox/NVActivityIndicatorView/issues/293#issuecomment-537514061).

**Comment by ninjaprox** [comment]
My opinion regarding this https://github.com/ninjaprox/NVActivityIndicatorView/issues/267#issuecomment-467465790
