### ISSUE TITLE
Can't access methods.

### ISSUE THREAD

**Issue by dspaces1** [ninjaprox/NVActivityIndicatorView#3]
Hello! I just pod installed and can't get access to anything from NVActivityIndicatorView except for NVActivityIndicatorViewVersionNumber. Any ideas?

**Comment by ninjaprox** [comment]
@dspaces1: There is no NVActivityIndicatorViewVersionNumber. You will check with this. Meanwhile, you could try manual installation and let me know if the issue's still there.

**Comment by ayushgoel** [comment]
I am also facing this issue.

**Comment by ninjaprox** [comment]
@dspaces1, @ayushgoel: The issue has been fixed. Let's update to the latest version.

**Comment by ayushgoel** [comment]
Thanks @ninjaprox :+1:
