### ISSUE TITLE
Animation appears at (0,0) of frame

### ISSUE THREAD

**Issue by martinliu0** [ninjaprox/NVActivityIndicatorView#30]
So this is how I set up the activity indicator:

```
let loading = NVActivityIndicatorView(frame: CGRectZero, type: .BallPulse, color: .whiteColor())
loading.translatesAutoresizingMaskIntoConstraints = false
signInButton.addSubview(loading)
loading.snp_makeConstraints{(make) -> Void in
    make.center.width.height.equalTo(signInButton)
}
loading.backgroundColor = UIColor.blueColor() // this is to see where the frame is.
loading.startAnimation()
```

But in the simulator it looks like this:

<img width="378" alt="screen shot 2016-04-08 at 11 51 45 am" src="https://cloud.githubusercontent.com/assets/2779550/14381714/54827fd0-fd80-11e5-91d7-ff8b7e8db8e5.png">

**Comment by ninjaprox** [comment]
It seems size of animation layer is calculated before the actual size of view is determined by autolayout.
One quick fix I suggest is to set `frame` to something else if the size is already known.

**Comment by martinliu0** [comment]
That works, thanks!
