### ISSUE TITLE
The project could not run. The error looks like this

### ISSUE THREAD

**Issue by WangYiOS** [ninjaprox/NVActivityIndicatorView#300]
![Snip20200320_4](https://user-images.githubusercontent.com/17872114/77130556-637b8e80-6a93-11ea-88b1-28452dfefec5.png)

Save the kids. Don't know what to do

**Comment by ninjaprox** [comment]
Please try again the latest `master` in Xcode 11.3. Let me know how it's going.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
