### ISSUE TITLE
NVActivityIndicatorView in SwiftUI

### ISSUE THREAD

**Issue by stefangerard** [ninjaprox/NVActivityIndicatorView#303]
Is there a way to use NVActivityIndicatorView in SwiftUI?

**Comment by emartinez-applaudostudios** [comment]
I think this post can help you out.
https://jetrockets.pro/blog/activity-indicator-in-swiftui

**Comment by ninjaprox** [comment]
@stefangerard Here you go [LoaderUI](https://github.com/ninjaprox/LoaderUI). It's still WIP but you can probably use it right away (SPM supported, CocoaPods not yet).
