### ISSUE TITLE
Issue with DEFAULT_PADDING

### ISSUE THREAD

**Issue by winkelsdorf** [ninjaprox/NVActivityIndicatorView#31]
Hi there,

today I stumbled about an glitch with the latest changes we made: The animations were cut off.

I checked the changes we made and found that the `animationRect` in `setUpAnimation()` has had a negative value for width and height.

The reason: You set a `DEFAULT_PADDING` of 25 instead of 0 what I proposed in my PR some weeks ago. My animation setup currently is only 25x25, thus the negative value.

Short question: Why default to 25? I think it's better to stick to 0 and leave it up to the user to adjust that default via Code or IB.

Cheers,
Frederik

**Comment by ninjaprox** [comment]
In fact, that was my mistake. Will update soon today.

**Comment by ninjaprox** [comment]
Updated on latest release.

**Comment by winkelsdorf** [comment]
Thank you very much! Well, that was not a real mistake, already thought you probably just committed a value for testing or something like that.

Keep up the good work 👍 

Cheers,
Frederik
