### ISSUE TITLE
'NVActivityIndicatorViewable' is deprecated

### ISSUE THREAD

**Issue by MiteshiOS** [ninjaprox/NVActivityIndicatorView#310]
I run example but it is showing NVActivityIndicatorViewable is deprecated.
Please take a look into screenshots.
<img width="1432" alt="Screenshot 2020-07-07 at 10 10 22 PM" src="https://user-images.githubusercontent.com/17427703/86814406-fe2dc680-c09e-11ea-9161-cd8adff71ed5.png">
<img width="1436" alt="Screenshot 2020-07-07 at 10 10 34 PM" src="https://user-images.githubusercontent.com/17427703/86814427-06860180-c09f-11ea-8459-3ecbf821a323.png">

**Comment by douglas-srs** [comment]
I wonder if there is something of upgrade guide since all my ViewControllers have 'NVActivityIndicatorViewable' and I also use the messages which I don't think is available on version 5

**Comment by summonerriftofficial** [comment]
use this

pod 'NVActivityIndicatorView', :git => 'https://github.com/ninjaprox/NVActivityIndicatorView.git', :tag => '4.8.0'

**Comment by ninjaprox** [comment]
Sorry for all inconvenience. Although `NVActivityIndicatorViewable` is marked as deprecated as per in [the release note](NVActivityIndicatorViewable), it's still useable, just bare with warnings. If you wish to use `NVActivityIndicatorViewable`, please use the following instead:

```
pod 'NVActivityIndicatorView/Extended'
```

**Comment by ninjaprox** [comment]
Close in favor of #315

**Comment by rizwan3395** [comment]
It should be open again, as after changing pod 'NVActivityIndicatorView/Extended' still giving deprecated issue on pod 'NVActivityIndicatorViewable'. Any fix upto now?

**Comment by i-conde** [comment]
@rizwan3395 Any fix upto now??
