### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by theofficejackpot** [ninjaprox/NVActivityIndicatorView#311]
https://nvactivityindicatorview.vinhis.me/. is 404.

Secondly, I just pulled 5.0.0 , coming from 4.8.0, and now getting 

```
let activityData = ActivityData(message: "Loading..", type: .circleStrokeSpin)
NVActivityIndicatorPresenter.sharedInstance.startAnimating(activityData)

```
Use of unresolved identifier 'NVActivityIndicatorPresenter'
Use of unresolved identifier 'ActivityData'

Can you please point me to the changes?

**Comment by summonerriftofficial** [comment]
same error

**Comment by summonerriftofficial** [comment]
pod 'NVActivityIndicatorView', :git => 'https://github.com/ninjaprox/NVActivityIndicatorView.git', :tag => '4.8.0'

**Comment by ninjaprox** [comment]
If you wish to use `NVActivityIndicatorPresenter`, please the following instead:

```
pod 'NVActivityIndicatorView/Extended'
```

**Comment by ninjaprox** [comment]
Close as the document is back, and for breaking changes in 5.0.0, please refer to its [release note](https://github.com/ninjaprox/NVActivityIndicatorView/releases/tag/5.0.0)
