### ISSUE TITLE
WHAT A STRANGE UPDATE

### ISSUE THREAD

**Issue by summonerriftofficial** [ninjaprox/NVActivityIndicatorView#313]
when you are planning to update  the  library make sure to include the old features not remove them for no reason or just don't do any changes cuz  everything was working perfectly before

I'm so sad that I have to use the old version with a branch link.

**Comment by skaunited** [comment]
I share exactly the same feeling with @summonerriftofficial,
I don't know for any reason you've changed the 'NVActivityIndicatorPresenter'. and the 'ActivityData' names but at least keep up to date from the Readme

**Comment by ninjaprox** [comment]
Sorry for all inconvenience. There is a release note for version [5.0.0](https://github.com/ninjaprox/NVActivityIndicatorView/releases/tag/5.0.0). Although `NVActivityIndicatorPresenter` is marked as deprecated, it's still usable, just bare with warnings. I'll update README for better communication of this breaking change.

**Comment by preetamjadakar** [comment]
Really surprised to see this change. the least expectation is not to plan deprecation without proper alternatives.

**Comment by gabors** [comment]
This is a really odd decision @ninjaprox 
For one I hate build warnings, your notes state to use NVActivityIndicatorViewExtended, but provide to example on how to use this with SwiftPM.

**Comment by ninjaprox** [comment]
Close in favor of #315
