### ISSUE TITLE
The Info.plist file is missing the required key: CFBundleVersion.

### ISSUE THREAD

**Issue by temoki** [ninjaprox/NVActivityIndicatorView#314]
After updating to version 5.0.0 from 4.8.0, the iTMSTransporter failed to upload binaries to App Store Connect with the following error

```
ERROR ITMS-90056: "This bundle Payload/{myapp}.app/Frameworks/NVActivityIndicatorView.framework is invalid.
The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"
```

- Installed by Carthage 0.35.0
- Xcode version is 11.6

**Comment by ninjaprox** [comment]
@temoki: It should be fixed in [5.0.1](https://github.com/ninjaprox/NVActivityIndicatorView/releases/tag/5.0.1).
