### ISSUE TITLE
No such module 'NVActivityIndicatorViewExtended'

### ISSUE THREAD

**Issue by kristoff2016** [ninjaprox/NVActivityIndicatorView#316]
Hi, 
After I updated the library I got this error `No such module 'NVActivityIndicatorViewExtended'`

Thank you

**Comment by kristoff2016** [comment]
Install `pod 'NVActivityIndicatorView/Extended'`

**Comment by kristoff2016** [comment]
still not working

**Comment by ninjaprox** [comment]
@kristoff2016 Have you tried cleaning Cocoapods setup? I tried with a fresh project, and it works well.

**Comment by kristoff2016** [comment]
I tried to close the project and clean build everything is still not working @ninjaprox

**Comment by ninjaprox** [comment]
@kristoff2016 How about just `import NVActivityIndicatorView`?

**Comment by kristoff2016** [comment]
it is working fine for `import NVActivityIndicatorView` only `NVActivityIndicatorViewExtended` can not import it

**Comment by kristoff2016** [comment]
I followed your example and your instructions
