### ISSUE TITLE
Error after update Xcode 

### ISSUE THREAD

**Issue by IsaevTA** [ninjaprox/NVActivityIndicatorView#318]
After updating Xcode 12, an error comes out: Could not find module 'NVActivityIndicatorView' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64
This was not the case on the previous version of Xcode 11.
Tell me how you can solve this?

**Comment by PierreBrisorgueil** [comment]
same error on my side, installed from carthage on xCode12

tempo fix : github "ninjaprox/NVActivityIndicatorView" ~> 4.8.0

**Comment by ninjaprox** [comment]
Maybe related to #319, should be fixed in `5.1.0`
