### ISSUE TITLE
[Swift Package Manager] Remove Support for iOS 8

### ISSUE THREAD

**Issue by rresma2** [ninjaprox/NVActivityIndicatorView#319]
Xcode versions 12 and onward drop support for iOS 8. I'd like to request to update the minimum iphone os deployment target  to iOS 9.

**Comment by twalshcbs** [comment]
Same here, basically will not allow us to use Swift Package Manager 
`warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'NVActivityIndicatorView' from project 'NVActivityIndicatorView')`

**Comment by ninjaprox** [comment]
`5.1.0` is out to drop support for iOS 8 🚀

**Comment by rresma2** [comment]
<img width="1008" alt="Screen Shot 2020-10-08 at 11 00 25 AM" src="https://user-images.githubusercontent.com/7170329/95496358-51493b00-0966-11eb-912a-36e2e663e7f8.png">

**Comment by rresma2** [comment]
Need to bump this to `.v9` @ninjaprox

**Comment by twalshcbs** [comment]
See my PR - https://github.com/ninjaprox/NVActivityIndicatorView/pull/321
