### ISSUE TITLE
Why pacman as the default?

### ISSUE THREAD

**Issue by pbassut** [ninjaprox/NVActivityIndicatorView#32]
Sure, pacman is awesome, childhood stuff and all.
But, for a production-ready application, who would use that?

Just a thought

**Comment by ninjaprox** [comment]
Just my preference. Any suggestion for default?

**Comment by pbassut** [comment]
I guess something that could be used in a production environment. Like something more formal. 
Don't get me wrong, I love pacman. It's just that 80% of the time people are gonna use this lib will have to change the default to something else.

Maybe BallScale is a good pick?

**Comment by ninjaprox** [comment]
I got your point, that pretty makes sense. Though people likely change to something else, it's still good idea to set default to something more common, as opposed to something fancy but little weird.
I will change the default to another. And thanks for your option as well.
