### ISSUE TITLE
Use of undeclared type 'NVActivityIndicatorViewable'

### ISSUE THREAD

**Issue by Afrah-Tayyab** [ninjaprox/NVActivityIndicatorView#322]
when i declare this delegate in my viewcontroller it prompt me an error i.e  Use of undeclared type 'NVActivityIndicatorViewable'

**Comment by ninjaprox** [comment]
Have you added `NVActivityIndicatorView/Extended` pod or `NVActivityIndicatorViewExtended` if using SPM as a dependency, and imported it?

**Comment by sashakid** [comment]
Говно на лопате, пользоваться стало невозможно после изменений, в документации ниче не написано.

**Comment by aqib399** [comment]
pod 'NVActivityIndicatorView/Extended'
