### ISSUE TITLE
Custome  Property

### ISSUE THREAD

**Issue by SchisandraX** [ninjaprox/NVActivityIndicatorView#325]
When I used this framework, I found that some properties could not be modified, such as layer.lineWidth, which I had to modify in the source code. I think this design is not friendly, so I hope you can make a property public for modification,

**Comment by ninjaprox** [comment]
Thanks for your interest and suggestion. You can check out my opinion regarding this at https://github.com/ninjaprox/NVActivityIndicatorView/issues/267#issuecomment-467465790.
