### ISSUE TITLE
M1 Mac - Could not find module 'NVActivityIndicatorView' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator

### ISSUE THREAD

**Issue by ccjiancui** [ninjaprox/NVActivityIndicatorView#327]

**Comment by ninjaprox** [comment]
I don't have an M1 Mac to check this issue. Maybe someone having one could help.

**Comment by lordlugo** [comment]
Either run using an actual device or run Xcode in rosetta(by going to the .app file and clicking "get info" the click "run under rosetta"

**Comment by fscaringi** [comment]
Hello everyone, unfortunately I also encounter this problem on the simulator, on the device instead no. On the simulator, however, by enabling Rosetta, I notice some strange behaviors, for example I can no longer paste tests etc. (xCode 13.2.1 on iPhone 13). Does anyone know if this library will receive an update to avoid Rosetta? Thank you

**Comment by jurvis** [comment]
hey folks, if anyone is seeing this issue, don't panic! there is a way to tell Cocoapods kindly to build `NVActivityIndicatorView` for your host architecture. In your `Podfile`, add the following to your post_install script: ` config.build_settings['ARCHS[sdk=iphonesimulator*]'] =  `uname -m`

such that it looks something like this:
```
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['ARCHS[sdk=iphonesimulator*]'] =  `uname -m`
  end
end
```

This essentially tells the pods project to build your libraries for your host machine's architecture (that is output by `uname -m`)
