### ISSUE TITLE
MIgration guide to v5

### ISSUE THREAD

**Issue by sidelux** [ninjaprox/NVActivityIndicatorView#328]
Hi,
i would ask how can i migrate my ActivityIndicator from version older than 5, without using NVActivityIndicatorViewable.

Now i have:
`class NotificationController: UITableViewController, NVActivityIndicatorViewable {`

then
`startAnimating(CGSize(width: 30, height: 30), type: NVActivityIndicatorType.ballPulse, color: UIColor.black, backgroundColor: UIColor.white)`

and
`self.stopAnimating()`

Any idea?
Thanks a lot.

**Comment by ninjaprox** [comment]
If you wish to continue using `NVActivityIndicatorViewable` and you're using CocoaPods, please use `pod 'NVActivityIndicatorView/Extended'`.
