### ISSUE TITLE
Swift language version not supported.

### ISSUE THREAD

**Issue by faiyaz-esignature** [ninjaprox/NVActivityIndicatorView#329]
Im currently in xcode 9.2 running swift 3.2 but the pod nvavtivityindicatorview is not supporting. What should i do?

**Comment by ninjaprox** [comment]
I'd recommend updating to the latest Xcode and Swift. If it's not possible, you still can use version [3.7.0](https://github.com/ninjaprox/NVActivityIndicatorView/releases/tag/3.7.0) and below.
