### ISSUE TITLE
how to set circleStrokeSpin stroke width

### ISSUE THREAD

**Issue by 2227322717** [ninjaprox/NVActivityIndicatorView#332]
how to set circleStrokeSpin stroke width
![image](https://user-images.githubusercontent.com/60668606/119116165-8c622f80-ba5a-11eb-9b02-fd3a99a6fdd4.png)

**Comment by ninjaprox** [comment]
Sorry, it's not supported. You can only change type, size and padding of animations.

**Comment by sunweiliang** [comment]
> how to set circleStrokeSpin stroke width ![image](https://user-images.githubusercontent.com/60668606/119116165-8c622f80-ba5a-11eb-9b02-fd3a99a6fdd4.png)

case .stroke:
            path.addArc(withCenter: CGPoint(x: size.width / 2, y: size.height / 2),
                        radius: size.width / 2,
                        startAngle: -(.pi / 2),
                        endAngle: .pi + .pi / 2,
                        clockwise: true)
            layer.fillColor = nil
            layer.strokeColor = color.cgColor
            layer.lineWidth = 2 // stroke width
        }
