### ISSUE TITLE
Unknown class NVActivityIndicatorView in Interface Builder file

### ISSUE THREAD

**Issue by jacobarvidsson** [ninjaprox/NVActivityIndicatorView#34]
Installing NVActivityIndicatorView using Carthage gives me this error. I've tried most things in these threads: http://stackoverflow.com/questions/33033129/xcode-7-1-swift-2-unknown-class-in-interface-builder-file, http://stackoverflow.com/questions/24924966/xcode-6-strange-bug-unknown-class-in-interface-builder-file ... Any ideas?

**Comment by jacobarvidsson** [comment]
So I got it to work by doing it the manual way, copying the folder into my project, but would have loved if it worked with Carthage.

**Comment by ninjaprox** [comment]
@jacobarvidsson: I tried setting `Module` in `Custom Class` to `NVActivityIndicatorView`, it works then. Let's try it and let me know if this helps out.

**Comment by maurovz** [comment]
Thanks @ninjaprox that solved my issue.

**Comment by alanscarpa** [comment]
@ninjaprox Also tried that - but no luck.  Still getting Unknown class in Interface Builder file.  Specifically when I try and call a method on my view, such as animating = true.

**Comment by ninjaprox** [comment]
@alanscarpa Could you give steps to reproduce your issue? I tried again the above solution in new plain project and it worked well.

**Comment by rsomlette** [comment]
I've got the same issue using CocoaPods. If I add the NVActivityIndicatorView in the storyboard I get the error whereas if I add it programatically everything works fine.
`Unknown class NVActivityIndicatorView in Interface Builder file.`
However creating a custom class inheriting from NVActivityIndicatorView did the trick...

**Comment by ninjaprox** [comment]
@Niphery: Have you tried https://github.com/ninjaprox/NVActivityIndicatorView/issues/34#issuecomment-213728956? This may also work.

**Comment by jlubeck** [comment]
I was getting a crash (unknown method sent to instance) when adding the view to the storyboard and trying to start animation from my class. Setting the Module to NVActivityIndicatorView fixed it for me. Thanks @ninjaprox

**Comment by ninjaprox** [comment]
It seems this issue is already solved in Xcode 8.
Close this, reopen if need be.

**Comment by ninjaprox** [comment]
Even in Xcode 8, setting Module to `NVActivityIndicatorView` is needed.

![screen shot 2016-10-24 at 9 58 15 pm](https://cloud.githubusercontent.com/assets/4948012/19648616/3a0c13d0-9a35-11e6-8017-ac609c4b5780.png)
