### ISSUE TITLE
Add Privacy Manifest

### ISSUE THREAD

**Issue by mvn-toantruong-dn** [ninjaprox/NVActivityIndicatorView#348]
Hello,
I am an employee of Monstarlab company. I have a question about the Privacy Manifest.

At WWDC23 Apple is requiring all api calls that fall under this ruleset https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278394
be added to a privacy manifest file.
Does NVActivityIndicatorView need to include this manifest?
Please let me know about your upcoming plans to apply the privacy manifest.

Thank you!!!

**Comment by ninjaprox** [comment]
@mvn-toantruong-dn The privacy manifest added in [5.2.0](https://github.com/ninjaprox/NVActivityIndicatorView/releases/tag/5.2.0). Let me know if it suffice

**Comment by alvincho617** [comment]
Hi, I've updated the library to 5.2.0 but I cannot seem to find the PrivacyManifest file. Could you point to where it is located in the Pods folder? Or is it invisible.
Thank you :)
