### ISSUE TITLE
[!] Unable to satisfy the following requirements

### ISSUE THREAD

**Issue by Lukaz32** [ninjaprox/NVActivityIndicatorView#4]
I keep getting the error message on trying to install the pod: `[!] Unable to satisfy the following requirements: - NVActivityIndicatorView required by Podfile`

This is how my Podfile looks like:
`target 'MyTarget' do`
    `pod "AFNetworking"`
  `pod "NVActivityIndicatorView"`
`end`

What am I missing?

**Comment by ninjaprox** [comment]
@Lukaz32: We are having a problem with pod, i'm trying fixing this issue. Meanwhile, you could install manually instead.

**Comment by ninjaprox** [comment]
@Lukaz32: The issues has been fixed. Update to the latest version and check README for details.

**Comment by Lukaz32** [comment]
Alright. Thanks 👍🏻
