### ISSUE TITLE
indicator is relative too big

### ISSUE THREAD

**Issue by skywalkerlw** [ninjaprox/NVActivityIndicatorView#43]
Only one line of code is used in my project:

`self.startActivityAnimating("Loading...",type: .LineScalePulseOut,color: UIColor.whiteColor(),padding: 0)`

However, it seems it's bigger than demo

![image](https://cloud.githubusercontent.com/assets/2090084/16513426/0bc9542a-3fa8-11e6-9715-1d9d0b79ffab.png)

**Comment by ninjaprox** [comment]
@wangbourne: You can use `padding` to reduce size of animation. Resizing animation in UI blocker will come in next version.
