### ISSUE TITLE
Using from ObjC ?

### ISSUE THREAD

**Issue by andres-cianio** [ninjaprox/NVActivityIndicatorView#49]
Hi there,

I'm using your controller in a swift project, and it's so awesome that I want to use it in another one, an ObjC one. From what I understand I only need to import the framework and I'll be set to go. [(doc)](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html)

But for some reason I can't set the type of the view. Ok, fine, I'll use the default one. But when trying to go ahead, I find out I can't even init the view. I tried both `[[NVActivityIndicatorView alloc] initWithFrame:CGRectMake(0, 0, 20, 20)];` and `[[NVActivityIndicatorView alloc] init];` to no avail.

Is there something else I should be doing? Thanks in advance!

**Comment by ninjaprox** [comment]
@AndresCianio: Because of using some Swift features, e.g. Enum with methods, default value for parameter, etc, I'm afraid using the control in ObjC has limits and it only support minimal functionalities. Please correct if I'm wrong. However, if you can think of ways to give more support to ObjC, PR is welcome.

**Comment by andres-cianio** [comment]
I really don't know how the whole Swift -> ObjC conversion works. Thought there might be some kind of issue with the configuration or something like that. 
In any case, I'll try to dig deeper and let you know with a PR if I find something useful.
Cheers!

**Comment by renetik** [comment]
So not possible to use in objective-c ? I believe it's possible if implemented.

**Comment by ninjaprox** [comment]
@rene-dohan: It's still possible to use in ObjC, with limit though. PR is welcome if you would like to make it fully support ObjC.
