### ISSUE TITLE
Carthage support 

### ISSUE THREAD

**Issue by MarvinNazari** [ninjaprox/NVActivityIndicatorView#5]
Would be awesome to have Carthage support :heart:

**Comment by ghost** [comment]
Hey,

Just got this error:

Dependency "NVActivityIndicatorView" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/ninjaprox/NVActivityIndicatorView/issues/new

**Comment by ninjaprox** [comment]
@iagomr: Could you create a new issue for this? Then we can mention the maintainers in. Thanks,
