### ISSUE TITLE
Swift 3 in Xcode 8 beta 6

### ISSUE THREAD

**Issue by sagaya** [ninjaprox/NVActivityIndicatorView#52]
Am getting a lot of error with xcode 8 beta 6

**Comment by ninjaprox** [comment]
@cosmo1234: It's supposed to be solved on 3.x releases.

**Comment by bcamur** [comment]
Hi, any updates on Xcode 8 beta 6 compatibility?

**Comment by ninjaprox** [comment]
@bcamur: Let's try `swift3` branch. There's also a PR for this but haven't yet merged.

**Comment by bcamur** [comment]
I have tried but it doesn't compile, I guess the PR you mentioned will solve the issue indeed.

**Comment by ninjaprox** [comment]
@bcamur: Guess so. Just merged #53, go check `swift3` branch, I think it would help.

**Comment by bcamur** [comment]
Yeah it works after the merge , thank you very much for the help.
