### ISSUE TITLE
View is hidden by the stopAnimation method?

### ISSUE THREAD

**Issue by whisper-bye** [ninjaprox/NVActivityIndicatorView#55]
@ninjaprox 
// this is my test code

``` swift
self.activityIndicatorView.startAnimation()
self.activityIndicatorView.hidesWhenStopped = false

dispatch_after(dispatch_time(DISPATCH_TIME_NOW, Int64(NSEC_PER_SEC * 3)), dispatch_get_main_queue()) {
    self.activityIndicatorView.stopAnimation()
}
```

Even if I wrote self.activityIndicatorView.hidesWhenStopped = false, The view is still hidden?

**Comment by ninjaprox** [comment]
@whisper-bye: Just checked the code

``` swift
public func stopAnimation() {
    self.layer.sublayers = nil
    self.animating = false
    if hidesWhenStopped && !hidden {
        hidden = true
    }
}
```

When `stopAnimation()` is called, it removes all sublayers. That is why the view looks like hidden regardless `hidesWhenStopped`. Anyway, I will refine this method and behavior, but PR is always welcome.

**Comment by ninjaprox** [comment]
@whisper-bye: I've decided to remove `hidesWhenStopped` in next major release (3.x). The expected behavior now should be that before starting and stopping animating, nothing should be appeared but its background color. Also considering to hide the view itself before starting and after stopping.

**Comment by whisper-bye** [comment]
@ninjaprox 
Thanks for your work. I will check it out later.

**Comment by otymartin** [comment]
@ninjaprox For some reason, my indicator does not hide when i call `self.activityIndicator.stopAnimating()`

UPDATE:
Nevermind, lousy programming from yours truly 😅

**Comment by ninjaprox** [comment]
@otymartin: What could I do to improve it?

**Comment by otymartin** [comment]
@ninjaprox it's perfect actually, I haven't had any problems with it at all. One usecase I'm going to attempt (It may be outside the focus scope) is at `startAnimating` -> I would like to automatically blur the view below. I use this library for video so while buffering, it makes for a nice effect.

Thanks alot for the library btw 💯

**Comment by ninjaprox** [comment]
@otymartin: Thanks! Perhaps I think that's good idea to add. I will try, PR is welcome though. 😄

**Comment by otymartin** [comment]
@ninjaprox I would but Im too new to swift & github (programming in general)😫🙈
