### ISSUE TITLE
NVActivityIndicatorViewable over navigationbar

### ISSUE THREAD

**Issue by malkabani** [ninjaprox/NVActivityIndicatorView#56]
hi
i use NVActivityIndicatorViewable to block UI
but alpha view not cover navigationbar
what is the problem???

**Comment by ninjaprox** [comment]
@malkabani: What version are you using? I think it already fixed in `2.10` as this PR #50.

**Comment by malkabani** [comment]
I think its last version

```
pod 'NVActivityIndicatorView'
```

**Comment by ninjaprox** [comment]
@malkabani: I checked `2.10` with simplest case `UINavigationControllerView -> UIControllerView` and it worked properly. Could you check again or give more detail for investigating?

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
