### ISSUE TITLE
Add delays to start and stop

### ISSUE THREAD

**Issue by dernster** [ninjaprox/NVActivityIndicatorView#57]
Hi! It would be awesome to have support for use cases where:
1. If the time difference between the `startActivityAnimating` and `stopActivityAnimating` calls is below certain threshold (e.g 200 ms), then do not display the corresponding `NVActivityIndicatorView` instance.
2. Once the `NVActivityIndicatorView` is shown, have it stay visible for a minimum amount of time in order to avoid fast flashes showing and hiding.

As a user, I would like to configure those time thresholds as a general setting, but also have the option to override those in particular calls. For instance, if I know that certain network call will last a considerable amount of time, then I would like to show the loading view instantly.

I could try adding it and then submit a pull request. What do you think?

**Comment by dernster** [comment]
[#58](https://github.com/ninjaprox/NVActivityIndicatorView/pull/58)

**Comment by ninjaprox** [comment]
@dernster: It's nice idea. For the threshold of time difference, however, I wonder how user can know how long an activity will be lasting and set appropriate value?

**Comment by dernster** [comment]
@ninjaprox Thanks! I believe that it should be set having in mind something like "If my activity lasts less than 200 ms, then do not even display it". We don't want to bother the real user of the app showing a loading screen if one particular activity lasts for so short. I mean, we can't really know how long an activity will take but we can think about what the minimum duration of an activity is to be worth showing it. What do you think?

**Comment by ninjaprox** [comment]
@dernster: Now it makes sense to me. Gonna merge the PR and have it in next version.

**Comment by ninjaprox** [comment]
@dernster: I wrote some tests for your new feature and think you would be interested to check out. It's on `features/UI-blocker` branch.

**Comment by dernster** [comment]
@ninjaprox I've just reviewed. All tests seems to be good, great job! If I run them separately they all pass, although if I run them all at once some of them fails. Any idea?

Also I'm wondering why this line of code is necessary:

``` swift
let timeInterval: NSTimeInterval = (_timeInterval == 0) ? 0.1 / 1000 : Double(_timeInterval) / 1000
```

why we can't just pass the timeInterval as zero?

**Comment by ninjaprox** [comment]
@dernster: It also happens sometime to me. I think it's due to the timeout. Currently the timeout is quite close to the waiting time. I tried setting to 1.5 and it seemed to be good.

And for the `timeInterval`, I found this in documentation.

> The number of seconds between firings of the timer. If ti is less than or equal to 0.0, this method chooses the nonnegative value of 0.1 milliseconds instead.

Not sure if I'm understanding correctly. Please fix if I'm wrong.

**Comment by dernster** [comment]
@ninjaprox I'm trying to figure out why the tests don't run all at once.

About the timeInterval, I think that it would be better to do just:

``` swift
return NSTimer.scheduledTimerWithTimeInterval(Double(_timeInterval) / 1000, target: self, selector: selector, userInfo: data, repeats: false)
```

and if `_timeInterval == 0` then the actual implementation of `scheduledTimerWithTimeInterval` will decide what to do with that (it will use 0.1 ms internally). I think is a better approach since this implementation could potentially change in the future. What do you think?

**Comment by dernster** [comment]
@ninjaprox I've just checked out the latest changes, all test are working fine (I've tried with and without my suggested change in the previous comment). Just don't forget to use the helper `createActivityData(...)` at `NVActivityIndicatorPresenterTests`. Great work 👍

**Comment by ninjaprox** [comment]
@dernster: Thanks for you correction and reminder, I almost forgot the helper 😄.
