### ISSUE TITLE
Dragged files into project, can't figure out how to use them

### ISSUE THREAD

**Issue by ollybeck** [ninjaprox/NVActivityIndicatorView#66]
```
class ViewController: UIViewController, UIImagePickerControllerDelegate, UINavigationControllerDelegate {

    @IBOutlet weak var imageView: UIImageView!
    let imagePicker = UIImagePickerController()
    @IBOutlet var spinner: UIActivityIndicatorView!
    @IBOutlet weak var textResults: UITextView!
    @IBOutlet weak var wordCount: UILabel!
    @IBOutlet weak var textFoundLabel: UILabel!
    @IBOutlet var activityIndicator: NVActivityIndicatorView! //Use of undeclared type 'NVActivityIndicatorView'
```

I started by making a UIView in storyboard and changing its class to 'NVActivityIndicator' in the file inspector. Then I control-dragged it to my ViewController.swift as an IBOutlet and the code will not compile. I tried to add 'NVActivityIndicator' to the class but end up with 'no such module' error. 

The 'NVActivityIndicatorView' folder is copied into my Xcode project, I'm not using pods.

I might be doing this completely wrong, I'm new to this – any help would be appreciated. 
(using Xcode 8 GM)

**Comment by ninjaprox** [comment]
@adamgrav: Have you checked if added files in `NVActivityIndicatorView` into Compile Sources in Build Phases? By using Xcode 8 GM, you might want to check `swift2.3` or `swift3` branch instead.

**Comment by ollybeck** [comment]
@ninjaprox It's working now! I ended up needing to drag each individual .swift file into the Compile Sources, it wouldn't read the folder I added. Thank you!
