### ISSUE TITLE
Xcode 8 and Swift 3.0?

### ISSUE THREAD

**Issue by chrisbull** [ninjaprox/NVActivityIndicatorView#68]
Any plans to update to Xcode 8 and Swift 3.0 any time soon?

**Comment by ninjaprox** [comment]
@chrisbull: Sure. I guess within next week.

**Comment by ninjaprox** [comment]
@chrisbull: Temporarily, please use `pod 'NVActivityIndicatorView', :git => 'https://github.com/ninjaprox/NVActivityIndicatorView.git', :branch => 'swift3'`

**Comment by ninjaprox** [comment]
The `master` branch now is updated to support Swift 3.

**Comment by MchlG** [comment]
i ran pod update and installed the latest pod but am still getting at least 30 errors in Xcode 8 swift 3.0 . Do you know when this may be fixed? Thanks

**Comment by ninjaprox** [comment]
@MchlG: Have you specified `master` branch instead of using latest version? Please check my comment above.

**Comment by MchlG** [comment]
got it thank you!

**Comment by LadyDeveloper** [comment]
I have this error using swift-3 branch 
<img width="994" alt="schermata 2016-09-19 alle 14 51 41" src="https://cloud.githubusercontent.com/assets/11472348/18632628/a680e460-7e78-11e6-987c-3e26439ea0c7.png">
How I can fix it?

**Comment by ninjaprox** [comment]
Version`v3.0` with Xcode 8 and Swift 3 support is now live. 🎉
