### ISSUE TITLE
Swift 2.3 compatible ?

### ISSUE THREAD

**Issue by yangzhixiao** [ninjaprox/NVActivityIndicatorView#70]

**Comment by ninjaprox** [comment]
@yangzhixiao: Sure, please check out `swift2.3` branch. Let me know if you get any issue.

**Comment by yangzhixiao** [comment]
It done... ths
pod 'NVActivityIndicatorView', :git => 'https://github.com/ninjaprox/NVActivityIndicatorView.git', :branch => 'swift2.3'
