### ISSUE TITLE
Long compile time in Pacman

### ISSUE THREAD

**Issue by spensko** [ninjaprox/NVActivityIndicatorView#72]
Hello. Compiling of NVActivityIndicatorAnimationPacman.swift takes a lot of time 

```
3633.1ms /Pods/NVActivityIndicatorView/NVActivityIndicatorView/Animations/NVActivityIndicatorAnimationPacman.swift:61:10    func circleInLayer(_ layer: CALayer, size: CGSize, color: UIColor)

3615.6ms    /Pods/NVActivityIndicatorView/NVActivityIndicatorView/Animations/NVActivityIndicatorAnimationPacman.swift:18:10 func pacmanInLayer(_ layer: CALayer, size: CGSize, color: UIColor)

3515.1ms    /Pods/NVActivityIndicatorView/NVActivityIndicatorView/Animations/NVActivityIndicatorAnimationPacman.swift:18:10 func pacmanInLayer(_ layer: CALayer, size: CGSize, color: UIColor)

3331.8ms    /Pods/NVActivityIndicatorView/NVActivityIndicatorView/Animations/NVActivityIndicatorAnimationPacman.swift:61:10 func circleInLayer(_ layer: CALayer, size: CGSize, color: UIColor)
```

for example another animation only 130ms

`130.8ms /Pods/NVActivityIndicatorView/NVActivityIndicatorView/Animations/NVActivityIndicatorAnimationOrbit.swift:29:10 func ring1InLayer(_ layer: CALayer, size: CGSize, color: UIColor)`

**Comment by ninjaprox** [comment]
@spensko: Thanks for you report! I investigated and optimized the compile time. This is mainly because of math calculations and can also be applied to optimize other files, especially `NVActivityIndicatorShape`.

**Comment by spensko** [comment]
Thanks! Swift really not good at basic math :)
