### ISSUE TITLE
Xcode8 swift3 problem

### ISSUE THREAD

**Issue by skywalkerlw** [ninjaprox/NVActivityIndicatorView#74]
i'm using:
Xcode8
swift: 3
cocoapods:1.1.0 rc2
NVActivityIndicatorView: 3.0
iPhone7 simulator

i have other frameworks in pod files, but only NVActivityIndicatorView has following errors when trying to build in Xcode

Undefined symbols for architecture x86_64:
  "(extension in NVActivityIndicatorView):NVActivityIndicatorView.NVActivityIndicatorViewable<A where A: __ObjC.UIViewController>.stopAnimating () -> ()", referenced from:
      Test.MainViewController.((fetchData in _429C5DB4CBE3D572A146F1757B8C8AAF) () -> ()).(closure #2).(closure #1).(closure #1) in MainViewController.o
  "(extension in

**Comment by skywalkerlw** [comment]
finally, my temp solution is to include source code directly into my project, rather than via cocoapod. However, i'm still expecting to use pod later :)

**Comment by ninjaprox** [comment]
@wangbourne: Could you try clear the project, delete `Pods` folder, then install pods again? Let me know if it helps.

**Comment by skywalkerlw** [comment]
yes, i have tried many times even after rebooting mac, it does not work

**Comment by ninjaprox** [comment]
@wangbourne: Could you send the snippet where you're using `NVActivityIndicatorView`? I tried myself with the simplest case and it works well.

**Comment by jwelton** [comment]
I too seem to be getting this issue, however for me it only seems to happen when in an extension. For example, I extend from `UIViewController` to implement `NVActivityIndicatorViewable`. In my example, I only get the error when calling something within the library, such as `stopAnimation()`. It's worth nothing, I have used Carthage to install, not Cocoapods.

**Comment by ninjaprox** [comment]
@jwelton: I tried with this snippet

``` swift
class ViewController: UIViewController, NVActivityIndicatorViewable {

    override func viewDidLoad() {
        super.viewDidLoad()

        let view = NVActivityIndicatorView(frame: CGRect(x: 100, y: 100, width: 100, height: 100))

        view.color = UIColor.red
        view.startAnimating()
        self.view.addSubview(view)
    }

    @IBAction func buttonDidTouch(button: UIButton) {
        startAnimating()
    }
}
```

and it works well. Wonder if your example looks like this?

**Comment by jwelton** [comment]
@ninjaprox That's different to mine. Mine was in an extension to UIViewController. For example:

``` swift
extension UIViewController: NVActivityIndicatorViewable {
    func showAnimation() {
        // Code here to show controller
    }
}
```

**Comment by ninjaprox** [comment]
@jwelton: `NVActivityIndicatorViewable` itself is both protocol and extension that add method to `UIViewController` ([here](https://github.com/ninjaprox/NVActivityIndicatorView/blob/master/NVActivityIndicatorView/NVActivityIndicatorViewable.swift#L18)). So I guess the above code is invalid in Swift that causes compile error. If it's `UIViewController`, it's no need to do as above. However, that's still applicable for subclass of `UIViewController`. For example

``` swift
class ViewController: UIViewController { }
extension ViewController: NVActivityIndicatorViewable {
    fun showAnimation() {
        // Code here to show controller
    }
}
```

I suggest using `NVActivityIndicatorPresenter` instead if the above is your need.

**Comment by jwelton** [comment]
Tbh it could of been `NVActivityIndicatorPresenter` that I was using anyway. I was writing the above from memory, so must of just got the naming wrong.

**Comment by ninjaprox** [comment]
Could you help check again and update later?

**Comment by jwelton** [comment]
@ninjaprox I've just checked the git history. Actually my original code was correct. I was inheriting from NVActivityIndicatorViewable, which would tie in with what you were saying. For completeness, here was my code (not working):

``` swift
import UIKit
import NVActivityIndicatorView
extension UIViewController: NVActivityIndicatorViewable {
    func presentLoadingView() {
        startActivityAnimating(CGSize(width: 50, height: 50), message: nil, type: .BallGridPulse, color: .whiteColor(), padding: 0)
    }
    func dismissLoadingView() {
        stopActivityAnimating()
    }
}
```

I guess that would mean I was conforming `UIViewController` to `NVActivityIndicatorViewable` twice. Makes sense for it to fail really.

**Comment by ninjaprox** [comment]
@jwelton: Thanks for your clarification.
@wangbourne: Are you using the same way we've been discussing here?

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
