### ISSUE TITLE
startAnimating in NVActivityIndicatorViewable

### ISSUE THREAD

**Issue by Pistacchione** [ninjaprox/NVActivityIndicatorView#75]
Hi,

is it possible to change the background color of loading panel when is called with startAnimating inside a NVActivityIndicatorViewable conform class?

Thanks

**Comment by ninjaprox** [comment]
@Pistacchione: Unfortunately not for now. PR is always welcome though.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
