### ISSUE TITLE
Extraneous argument label 'size:' in call

### ISSUE THREAD

**Issue by skrosoft** [ninjaprox/NVActivityIndicatorView#76]
Hello,

I have updated my project to Swift version 3 and NVActivityIndicatorView 9 issues

![image](https://cloud.githubusercontent.com/assets/4645565/18973691/33332400-8675-11e6-8fb3-fa5abf8d4549.png)

It seems that the "size:" label is now useless. Any idea?

Edit: I have 15 issues

Vincent

**Comment by ninjaprox** [comment]
@skrosoft: What Cocoapods version are you using? I guess `1.1.0.rc.2`will solve this.

**Comment by skrosoft** [comment]
@ninjaprox i am already using version 1.1.0.rc.2.

**Comment by skrosoft** [comment]
I think you should remove all your "size:" label.

Example: https://github.com/ninjaprox/NVActivityIndicatorView/blob/master/NVActivityIndicatorView/Animations/NVActivityIndicatorAnimationCubeTransition.swift line 64

The same occurs with the "angle:" label in another files.

**Comment by ninjaprox** [comment]
@skrosoft: It's needed as [here](https://github.com/ninjaprox/NVActivityIndicatorView/blob/master/NVActivityIndicatorView/NVActivityIndicatorShape.swift#L23). How about clean up project, pods, deintegrate then try again?

**Comment by skrosoft** [comment]
Maybe the XCode automatique converter to Swift 3 has modified your code.

I have removed the pod from the Podfile, executed "pod install"
I have added the pod in the Podfile, executed "pod install"

It seems to be now ok, thank you.

**Comment by ninjaprox** [comment]
You're welcome! Thanks for reporting! Let me know if encountering any other issues.
