### ISSUE TITLE
Orientation Support

### ISSUE THREAD

**Issue by iHamzaaK** [ninjaprox/NVActivityIndicatorView#78]
Can u please advise me how to handle orientation of the NvActivityIndicatorView. For now the view is displaced when i switch to landscape mode.
@ninjaprox 
Thanks in advance.

**Comment by ninjaprox** [comment]
@kevinonik: There's a workaround here #77, you could try. I'll add orientation support in next version.

**Comment by ninjaprox** [comment]
@kevinonik: It seems to work without any addition. I checked it myself however if you still have this problem, please let me know. Close this, reopen if need be.
