### ISSUE TITLE
Custom message label width?

### ISSUE THREAD

**Issue by devSC** [ninjaprox/NVActivityIndicatorView#79]

**Comment by zhenjiangliu24** [comment]
I have the same question, cause in iphone SE, the message text will be truncated if message too long.

**Comment by ninjaprox** [comment]
It's not supported at the moment. PR is always welcome though.

**Comment by ninjaprox** [comment]
@devSC @zhenjiangliu24: Instead of custom message width, now you can set custom font. The width will be auto adjusted to the message but not larger than screen's width. `3.1` is shipped with this feature. 🚀

**Comment by devSC** [comment]
@ninjaprox  Thanks.
