### ISSUE TITLE
Swift 2.0

### ISSUE THREAD

**Issue by Ewg777** [ninjaprox/NVActivityIndicatorView#8]
Any luck that this library is available in Swift 2.0?

**Comment by ninjaprox** [comment]
@Ewg777: Sure, you can contribute if you want. You're welcome.

**Comment by Ewg777** [comment]
@ninjaprox seems https://github.com/ninjaprox/NVActivityIndicatorView/pull/2 good

**Comment by adamcjohnson** [comment]
Definitely hoping this can get merged in soon.

**Comment by ninjaprox** [comment]
@adamcjohnson: just wait few more weeks till Swift 2.0 official release

**Comment by Ewg777** [comment]
Swift 2.0 officially released

**Comment by ninjaprox** [comment]
@Ewg777, @adamcjohnson: now in Swift 2.0 :)
