### ISSUE TITLE
NVActivityIndicatorView added with storyboard sometimes ignore contraints

### ISSUE THREAD

**Issue by LarsWith** [ninjaprox/NVActivityIndicatorView#80]
I have noticed that if I add the NVActivityIndicatorView with storyboard it sometimes ignores the contraint I set in storyboard. I dont get any error/warnings but a 55x55 loader ended up being 1000x1000 in size and stuck to the bottom left corner.

I think this happens when you have alot of UI going on in your VC added with storyboard - I dont see this happen when added with code or in light VC's

**Comment by ninjaprox** [comment]
@LarsWith: There's a related issue #73.

**Comment by ninjaprox** [comment]
Close this, let's discuss on #73.
