### ISSUE TITLE
Setting user defined inspectables in interface builder causes crash.

### ISSUE THREAD

**Issue by the-freshlord** [ninjaprox/NVActivityIndicatorView#83]
Hi,

when creating an instance in interface builder, and setting the inspected properties available, I get this error in the console when running an app that I am building: `
Failed to set (color) user defined inspected property on (UIView): [<UIView 0x7b63ba40> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key color.
2016-10-13 16:41:27.470 
`.

**Comment by GuilhermeMachado** [comment]
Same problem

**Comment by ninjaprox** [comment]
@eman6576, @GuilhermeMachado: Setting Module to `NVActivityIndicatorView` will help. Reference #34.

![screen shot 2016-10-24 at 9 58 15 pm](https://cloud.githubusercontent.com/assets/4948012/19648587/1a522e62-9a35-11e6-803e-90b4e90ce4fa.png)

**Comment by ghost** [comment]
Even set the module, the app dont crash, but this warning still print at my console.
