### ISSUE TITLE
Swift 3.0 compiler error

### ISSUE THREAD

**Issue by ghost** [ninjaprox/NVActivityIndicatorView#84]
I have got this error after pulling mater branch with pod file.
I have used `pod 'NVActivityIndicatorView'` and got this compiler error.

```
'shared' is unavailable: Use view controller based solutions where appropriate instead.
```

I got this errors on NVActivityIndicatorPresenter line 149, 153 in show / hide methods.

**Comment by ninjaprox** [comment]
@fxpage: Please try cleaning up project as well as pods, then install again with latest CocoaPods. Reference #76.

**Comment by ghost** [comment]
@ninjaprox it worked! Thanks for your support.

**Comment by ghost** [comment]
@ninjaprox it doesn't bring me compile error, but it's nil during runtime.

```
UIApplication.shared.keyWindow = nil
```

I'm trying to integrate your indicator to iMessage app extension, and please let me know how can I handle this error.

**Comment by ninjaprox** [comment]
@fxpage: You're welcome 😄. If you're using in app extension, I suggest creating instance of `NVActivityIndicatorView` and using it directly as maybe there's no window in app extension, then `NVActivityIndicatorPresenter` won't work. Let me know if it helps.

**Comment by ghost** [comment]
@ninjaprox, Thanks for your update.
Can you post some sample code for creating instance?

**Comment by ninjaprox** [comment]
@fxpage: I think you can try checking [this](https://github.com/ninjaprox/NVActivityIndicatorView#initialization).

**Comment by ghost** [comment]
@ninjaprox, I have upgraded cocoapod version to 1.1.1 from 1.0.1, and I got the same issue.
I have cleaned up project as well as pods, then install again, but no luck.

Please let me know what should I do to fix the issue.
Thank you for your patience.

**Comment by ninjaprox** [comment]
@fxpage: You meant that you managed to fix the issue with CocoaPods `1.0.1` but it happened again with `1.1.1`?

**Comment by 0xc00010ff** [comment]
This is a valid issue- see line 162 and 167 of `NVActivityIndicatorPresenter.swift`.
`UIApplication.shared.keyWindow` will not compile for files included in an app extension.

There are ways around this- usually defining macros that allow compile-time inspection of if the current environment in an app extension. 
http://stackoverflow.com/questions/29605094/detect-whether-run-target-is-app-extension-or-ios-app

If a code approach is preferred, you can also traverse up the view hierarchy to the root view, which would allow drop-in compatibility with extensions, not needing macros for environment introspection.

**Comment by ninjaprox** [comment]
@0xc00010ff: There's another issue and discussion related to this at #119.
