### ISSUE TITLE
How to check animation is starting?

### ISSUE THREAD

**Issue by ghost** [ninjaprox/NVActivityIndicatorView#86]
Hi everybody
I can't find any method/property for check animating start in view? (like isAnimating)
for example start animating in viewWillAppear function and i want when tableview is reloading and finish work in didEndDisplaying func; stop animating...
Thank's

**Comment by ninjaprox** [comment]
@ghasim: Please check [README](https://github.com/ninjaprox/NVActivityIndicatorView#control) first. Let me know if it's what you're looking for.

**Comment by ghost** [comment]
[This](https://github.com/ninjaprox/NVActivityIndicatorView#control) solution is very bad. I had to define
`var activityIndicatorView = NVActivityIndicatorView(frame: frame, type: type, color: color, padding: padding)`
in viewDidLoad and when can't use activityIndicatorView in another function ! if define local variable
`let activityIndicatorView = NVActivityIndicatorView()` 
code is error: Cannot invoke initializer for type 'NVActivityIndicatorView' with no arguments
I want check animating like UI blocker func. like this code:
`if isAnimating{}`
Thanks

**Comment by ninjaprox** [comment]
@ghasim: Please give snippet, it helps figure out solution for your use case.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
