### ISSUE TITLE
pod try project sigabrt

### ISSUE THREAD

**Issue by smileatom** [ninjaprox/NVActivityIndicatorView#87]
dyld: Library not loaded: @rpath/NVActivityIndicatorView.framework/NVActivityIndicatorView
  Referenced from: /var/containers/Bundle/Application/3CD7E242-1093-4469-8A48-6EA1505B5307/NVActivityIndicatorViewDemo.app/NVActivityIndicatorViewDemo
  Reason: image not found

**Comment by ninjaprox** [comment]
@rendion: What pod version are you using? I tried with `1.1.1`, it worked then.

**Comment by smileatom** [comment]
Im on 1.1.1 as well.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
