### ISSUE TITLE
Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1

### ISSUE THREAD

**Issue by freegyp** [ninjaprox/NVActivityIndicatorView#89]

**Comment by ninjaprox** [comment]
@freegyp: I guess you're using Xcode 8.2. Please elaborate on this issue.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.

**Comment by freegyp** [comment]
Sorry I didn't check. I'm using Xcode 8.1 actually.

**Comment by freegyp** [comment]
It didn't have this problem when I tried to use Xcode 8. But it seems like I cannot deploy the project on my iPhone with system upgraded to 10.1.1 if I use the old Xcode 8. BTW, I need to reopen this issue now.

**Comment by ninjaprox** [comment]
@freegyp: How about explicitly set Swift version in Podfile? This might be the same problem with migration from Swift 2.x to 3.0.

**Comment by ninjaprox** [comment]
@freegyp: `3.1` is shipped with Swift `3.0.1`, hope this would help solve this issue.

**Comment by freegyp** [comment]
I'm sure I have updated it to 3.1 now, but it still have this problem.

**Comment by ninjaprox** [comment]
@freegyp: I tried with this spec Xcode 8.1, Swift `3.0.1`, Cocoapod `1.1.1` and `3.1` and it went well. I suggest cleaning pods and installing again. If still have issue, please provide more information such as screenshots, snippet, etc. to investigate.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
