### ISSUE TITLE
75 warnings in Xcode 8.2 Swift 3

### ISSUE THREAD

**Issue by MchlG** [ninjaprox/NVActivityIndicatorView#90]
I tried to use the most recent pod version pod 'NVActivityIndicatorView' in my Swift 3 project in Xcode 8.2 but i get 75 warnings and Xcode offers to "convert to latest syntax". I ran pod update and still get same errors. Isn't the project supposed to work in Swift 3?

**Comment by henryhardy** [comment]
Same issue.

**Comment by ninjaprox** [comment]
@MchlG: No, it isn't. The problem may be due to Xcode 8.2. If you try in Xcode 8.1 or 8.0, it's supposed to compile without any warning or error.

**Comment by MchlG** [comment]
Do you mean to say ... No, it is not supposed to wok with Swift 3?

**Comment by ninjaprox** [comment]
@MchlG: I meant it does support, sorry for misleading.

**Comment by MchlG** [comment]
Ok thanks, will give it a try in Xcode 8.1 soon

**Comment by ahaverty** [comment]
I'm hitting this issue in Xcode 8.2, but my colleague, also using 8.2, isn't seeing any issues.

**Comment by ahaverty** [comment]
I'm not sure why, but adding `source 'https://github.com/CocoaPods/Specs.git'` to my podfile prevented the convert popup in Xcode 8.2
I followed the readme of https://github.com/antoninbiret/ABSteppedProgressBar which was also throwing the convert popup.

**Comment by ninjaprox** [comment]
@ahaverty: Sorry, I haven't checked in Xcode 8.2 yet. However, as you described above, you could try `pod install --repo-update`, let me know the result.

**Comment by ahaverty** [comment]
Adding `source 'https://github.com/CocoaPods/Specs.git'` to my podfile actually fixed it. It must do something similar to `pod install --repo-update`? Thanks for the help
