### ISSUE TITLE
cannot use NVActivityIndicatorAnimationDelegate

### ISSUE THREAD

**Issue by stevenkitter** [ninjaprox/NVActivityIndicatorView#98]
i want to realize my own animation，but i can not access the delegate
![829fc90e-1bd5-4c37-b4ca-11ac16bb6d5b](https://cloud.githubusercontent.com/assets/12658782/21217866/5385fede-c2e9-11e6-923f-4ab8315aacd3.png)

**Comment by ninjaprox** [comment]
@stevenktter: At the moment, it doesn't support custom animation so `NVActivityIndicatorAnimationDelegate` isn't public. This feature may be opened in next version.
