### ISSUE TITLE
"Unknown class NVActivityIndicatorView in Interface Builder file" Error

### ISSUE THREAD

**Issue by ayunav** [ninjaprox/NVActivityIndicatorView#99]
Hi, 

Love your framework, and I was trying to set up a UIView property via IB. 

<img width="259" alt="screen shot 2016-12-15 at 12 51 16 pm" src="https://cloud.githubusercontent.com/assets/12476189/21235569/51245ef2-c2c5-11e6-8c7b-e7bcd8e6056d.png">

<img width="260" alt="screen shot 2016-12-15 at 12 51 33 pm" src="https://cloud.githubusercontent.com/assets/12476189/21235568/4f191558-c2c5-11e6-91f5-0ad3c03d9dc8.png">

But I get this error at runtime: 

Unknown class NVActivityIndicatorView in Interface Builder file.
Failed to set (typeName) user defined inspected property on (UIView): [<UIView 0x7fbcb062f970> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key typeName.
Failed to set (color) user defined inspected property on (UIView): [<UIView 0x7fbcb062f970> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key color.
Failed to set (padding) user defined inspected property on (UIView): [<UIView 0x7fbcb062f970> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key padding.

<img width="911" alt="screen shot 2016-12-15 at 12 49 49 pm" src="https://cloud.githubusercontent.com/assets/12476189/21235608/77cfd9c8-c2c5-11e6-99ff-14c31cad9352.png">

Do you have any tips on resolving this? Thanks!

**Comment by ninjaprox** [comment]
@ayunav: The first note in [Initialization](https://github.com/ninjaprox/NVActivityIndicatorView#initialization) mentions this so all things you need to do is to set `Module` to `NVActivityIndicatorView`. Hope this helps. 😄
